"""figures_en.py -- the English edition's redesigned figures.

These nine figures were redrawn for the Russian edition with rotational or mirror symmetry
(a spiral disc, a star fort, trines, a wheel, an octagon) and are generated here with the
same geometry and the English text. Curved labels are set letter by letter with widths
measured in the English edition's own font encoding (tools/curved_text.py, lang="en").

    python3 tools/figures_en.py        # writes the nine files into v3-figures/
"""
import math, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import curved_text as ct
ct.LANG = "en"
from curved_text import along, arc_label, width

OUT = pathlib.Path(__file__).resolve().parent.parent / "v3-figures"

def write(name, lines):
    (OUT / name).write_text("\n".join(lines) + "\n")
    print("wrote", name)

def star_pts(cx, cy, t, i, rot=0.0):
    return " -- ".join("(%.3f,%.3f)" % (cx + (t if k % 2 == 0 else i) * math.cos(math.radians(22.5 * k + rot)),
                                        cy + (t if k % 2 == 0 else i) * math.sin(math.radians(22.5 * k + rot)))
                       for k in range(16)) + " -- cycle"

# ------------------------------------------------------------------ 1: core to shell
def core_to_shell():
    rings = [
     ("Schema walls", "triggers, CHECK constraints, the partial unique index; C1--C10"),
     ("Cryptographic evidence", "ML-DSA signatures, custody, two witnesses, canonical signing"),
     ("Verification and status", "detached verifier, SDKs, conformance, status assertions, epochs"),
     ("Privacy boundary", "disclosure levels, unlinkable records, membership proofs"),
     ("Use", "wallet, presentations, relying-party API, auth broker"),
     ("Federation", "per-authority roots, manifests, directional attestations, feeds"),
     ("Transparency", "logs, signed heads, witnesses, gossip, equivocation proofs"),
     ("Institutions and operations", "registry, gateway, receipts, timestamps, signing; HA, DR, chaos, CI"),
     ("Cognition, boundaries, agents, the outside", "Atlas, Athena; what is refused; agents and personhood (built); strangers' software (dashed: not ours)"),
    ]
    CORE, STEP, TURN = 0.75, 1.0, 40
    o = ["% v3-figures/core-to-shell.tex: the concentric map of Polaris, drawn as a spiral galaxy.",
         "% Each ring's name is set along its own band and turned forty degrees further round than",
         "% the one inside it, so the nine names wind once around the disc from the core outward,",
         "% the order the paper is read in. Generated by tools/figures_en.py.",
         "\\begin{tikzpicture}"]
    shades = [26, 20, 16, 13, 10, 8, 6, 4, 2]
    for k in range(9, 0, -1):
        o.append("  \\fill[navymid!%d!white] (0,0) circle (%.3f);" % (shades[k-1], CORE + STEP*k))
    for k in range(1, 9):
        o.append("  \\draw[ring] (0,0) circle (%.3f);" % (CORE + STEP*k))
    o.append("  \\draw[ringfut] (0,0) circle (%.3f);" % (CORE + STEP*9))
    o.append("  \\fill[accent] (0,0) circle (%.3f);" % CORE)
    o.append("  \\node[font=\\footnotesize\\bfseries, text=white] at (0,0) {core};")
    for k, (name, _) in enumerate(rings, 1):
        c = CORE + STEP*(k-0.5)
        label = "%d. %s" % (k, name)
        assert width(label, "fb") < math.pi*c*28.4527*0.95, label
        t, _ = arc_label(label, "fb", (90 - (k-1)*TURN) % 360, round(c, 3), color="navydark", lift="-2.7pt")
        o.append("  " + t)
    t, _ = arc_label("read outward: each ring exists because the one inside it was not enough",
                     "kk", 90, round(CORE + STEP*9 + 0.45, 3), color="gold", lift="-1.8pt")
    o.append("  " + t)
    top = -(CORE + STEP*9) - 0.75
    rows = []
    for r in range(3):
        cells = []
        for c in range(3):
            i = r*3 + c; name, what = rings[i]
            cells.append("\\textbf{\\color{navydark}%d. %s}\\newline{\\color{steelgray}%s}" % (i+1, name, what))
        rows.append(" & ".join(cells))
    o.append("  \\node[anchor=north, font=\\scriptsize] at (0,%.2f) {%%\n"
             "    \\begin{tabular}{@{}>{\\centering\\arraybackslash}p{5.4cm}>{\\centering\\arraybackslash}p{5.4cm}>{\\centering\\arraybackslash}p{5.4cm}@{}}\n"
             "    \\multicolumn{3}{c}{\\textbf{\\color{accent}Core.} one \\code{IdentityToken} row and its \\code{TokenSignature}: a signed claim}\\\\[8pt]\n"
             "    %s\n    \\end{tabular}};" % (top, " \\\\[11pt]\n    ".join(rows)))
    o.append("\\end{tikzpicture}")
    write("core-to-shell.tex", o)

# ------------------------------------------------------------------ 5: the town
def town_map():
    T, I = 6.0, 4.75
    P = lambda a, r: "(%.3f:%.3f)" % (a, r)
    o = [r"""% v3-figures/town-map.tex: the walled town as a star fort.
% An eight-pointed wall: the four gates on the cardinal points, the four watchtowers on
% the diagonals, the hall at the centre and the five districts on a pentagon round it.
% The laws above the town are a crown of text over the fort; outsiders stand on an outer
% ring, and the second town is a smaller fort at the end of a one-way road.
% Generated by tools/figures_en.py.
\begin{tikzpicture}[
  wall/.style={draw=navydark, line width=2pt, fill=tabstripe, line join=miter},
  district/.style={draw=navymid, line width=0.7pt, rounded corners=2pt, fill=white, font={\scriptsize\hyphenpenalty=10000\exhyphenpenalty=10000}, align=center, inner sep=3pt, text width=2.95cm, minimum height=1.95cm},
  hall/.style={draw=accent, line width=1.4pt, circle, fill=accent, text=white, font=\bfseries\scriptsize, align=center, inner sep=2pt, text width=2.05cm},
  gate/.style={draw=navydark, line width=1pt, fill=gold, font=\tiny\bfseries, align=center, inner sep=2.5pt, text width=2.3cm},
  tower/.style={draw=navydark, line width=1pt, fill=navydark, text=white, font=\scriptsize\bfseries, align=center, inner sep=0pt, circle, minimum size=0.62cm},
  road/.style={draw=steelgray, line width=3pt, double=white, double distance=1pt},
  outsider/.style={text width=2.9cm, align=center},
]"""]
    o.append("\\draw[wall] %s;" % " -- ".join(P(22.5*i, T if i % 2 == 0 else I) for i in range(16)) + " -- cycle;")
    o[-1] = "\\draw[wall] " + " -- ".join(P(22.5*i, T if i % 2 == 0 else I) for i in range(16)) + " -- cycle;"
    o.append("\\draw[navydark, line width=0.4pt, opacity=0.35] (0,0) circle (3.15);")
    o.append("\\draw[classmark, line width=0.8pt] (28:7.05) arc[start angle=28, end angle=152, radius=7.05];")
    t, _ = arc_label("The laws above the town: the vocation and C1-C10 (MISSION.md), enforced in the schema", "fb", 90, 7.45, color="classmark", lift="-1.2pt"); o.append(t)
    t, _ = arc_label("and pinned by 313 invariant checks", "fb", 90, 7.95, color="classmark", lift="-1.2pt"); o.append(t)
    o.append("\\node[hall] (hall) at (0,0) {town hall record\\\\[1pt]{\\tiny\\mdseries IdentityToken +\\\\TokenSignature}};")
    districts = [("workshops", "epochs, permissions, recovery, duress"),
                 ("council chamber", "{\\tiny AgencyAlgorithmAuth, IssuerDiscretionPolicy, quotas}"),
                 ("archives", "{\\tiny append-only event logs, RetentionPolicy}"),
                 ("court records", "{\\tiny AuditAccessLog,\\\\DuressEvent,\\\\LifecycleArchiveCheckpoint}"),
                 ("registry office", "Athena views, the signed registry, the trust list")]
    for k, (name, body) in enumerate(districts):
        extra = ", text width=3.25cm" if name == "court records" else ""
        o.append("\\node[district%s] at %s {\\textbf{%s}\\\\[1pt]{\\scriptsize %s}};" % (extra, P(90 + 72*k, 3.15), name, body))
    gates = {90: ("issuance gate", "\\texttt{uc1\\_issue}, signing", "g1"),
             0: ("verification gate", "\\texttt{/api/v1/verify}", "g2"),
             270: ("exchange gate", "\\texttt{/api/v1/exchange}", "g3"),
             180: ("login gate", "auth broker, PKCE", "g4")}
    for a, (n, b, gid) in gates.items():
        o.append("\\node[gate] (%s) at %s {%s\\\\{\\mdseries %s}};" % (gid, P(a, T), n, b))
    for k, a in enumerate((45, 135, 225, 315), 1):
        o.append("\\node[tower] (t%d) at %s {W};" % (k, P(a, T)))
    o.append("\\node[humanbox, outsider] (holder) at %s {holder\\\\[-1pt]{\\tiny\\mdseries wallet file, presentation}};" % P(180, 8.75))
    o.append("\\draw[flow] (holder.east) -- (g4.west);")
    o.append("\\node[font=\\tiny\\itshape\\color{steelgray}, text width=2.9cm, align=center, anchor=north] at (holder.south) {enters by possession; a duress code looks like consent to the coercer};")
    o.append("\\node[extbox, outsider] (rp) at %s {relying party\\\\[-1pt]{\\tiny\\mdseries verifies offline with the detached verifier}};" % P(0, 8.75))
    o.append("\\draw[flow] (g2.east) -- (rp.west);")
    o.append("\\node[extbox, outsider] (wit) at %s {independent witnesses\\\\[-1pt]{\\tiny\\mdseries cosign heads, gossip, refuse a fork}};" % P(225, 8.9))
    o.append("\\draw[sees] (wit) -- (t3);")
    o.append("\\draw[wall, line width=1.2pt] %s;" % star_pts(8.35, -8.35, 1.85, 1.45))
    o.append("\\node[hall, text width=1.9cm, font=\\bfseries\\tiny] at (8.35,-8.35) {another authority\\\\{\\mdseries its own hall, its own key}};")
    o.append("\\draw[road] (t4) -- ($(8.35,-8.35)!1.5cm!(t4)$);")
    o.append("\\node[anchor=south west, align=left, inner sep=1pt] at (6.75,-6.0) {{\\tiny\\scshape\\color{gold}road: attestation}\\\\{\\tiny\\itshape\\color{steelgray}one way, one context}};")
    o.append("\\end{tikzpicture}")
    write("town-map.tex", o)

# ------------------------------------------------------------------ 6: outside witnesses
def outside_witnesses():
    R = 6.7
    cards = [
     (90, "a wallet nobody here wrote", "walt.id Wallet API v2",
      ["unmodified, at a pinned image digest", "exercised: \\code{polaris-oid4vp}",
       "\\textbf{\\code{200 authentic}}, six claims",
       "{\\color{classmark}control:} a different issuer key, \\code{400 refused}",
       "{\\color{classmark}control:} presented twice, refused"],
      "it refused Polaris first: a request-signing certificate with no \\code{digitalSignature} key usage"),
     (210, "a service somebody else runs", "OpenID Foundation hosted conformance suite",
      ["across the open internet, 15 September 2026", "exercised: \\code{polaris-oid4vp}, eleven modules",
       "\\textbf{seven negative modules \\code{PASSED}}, scored by the service",
       "{\\color{gold}four positive modules \\code{REVIEW}}", "\\textbf{certified 24 September 2026}, \\code{1.0.0rc7}"],
      "zero failures, zero warnings; two controls, one per direction"),
     (330, "a corpus somebody else wrote", "Project Wycheproof",
      ["ML-DSA-65 verification vectors, pinned commit", "exercised: both signature witnesses",
       "\\textbf{58 of 58 agree}", "accepting an invalid vector is a failure", "on every push"],
      "the primitive, not the protocol: no presentation was exchanged with anybody"),
    ]
    o = ["% v3-figures/outside-witnesses.tex: the three outside witnesses as a trine: three parties",
         "% of equal standing on an equilateral triangle inscribed in a circle, each joined to",
         "% Polaris at the centre. Generated by tools/figures_en.py.",
         "\\begin{tikzpicture}[",
         "  card/.style={extbox, text width=5.75cm, minimum height=4.75cm, align=left, inner sep=5pt},",
         "]",
         "\\begin{scope}[on background layer]",
         "  \\draw[gold, line width=0.6pt, dash pattern=on 3pt off 2pt] (0,0) circle (%.2f);" % R,
         "  \\draw[gold, line width=0.4pt, opacity=0.55] (90:%.2f) -- (210:%.2f) -- (330:%.2f) -- cycle;" % (R, R, R),
         "\\end{scope}"]
    for a, kick, title, rows, note in cards:
        o.append("\\draw[flow] (%d:%.2f) -- (%d:1.45);" % (a, R - 2.3 if a == 90 else R - 2.55, a))
        body = "\\\\[1pt]".join("{\\scriptsize %s}" % r for r in rows)
        o.append("\\node[card] (c%d) at (%d:%.2f) {{\\scriptsize\\scshape\\color{gold}%s}\\\\[2pt]{\\bfseries\\small %s}\\\\[3pt]%s\\\\[3pt]{\\tiny\\itshape\\color{steelgray}%s}};"
                 % (a, a, R, kick, title, body, note))
    o.append("\\draw[draw=navydark, line width=1.2pt, fill=accent, line join=miter] %s;" % star_pts(0, 0, 1.45, 1.1, 11.25))
    o.append("\\node[font=\\bfseries\\footnotesize, text=white] at (0,0) {Polaris};")
    o.append("\\node[faint, text width=13cm, align=center, anchor=north] at (0,-7.0) {none of the three is an audit, a pilot or an operator; the second led to one conformance certification of one package version, which is not an endorsement; the scoreboard holds each row with its date and with what it does not establish};")
    o.append("\\end{tikzpicture}")
    write("outside-witnesses.tex", o)

# ------------------------------------------------------------------ 8: holder flow
def holder_flow():
    R = 7.9
    cards = {
     90: ("layerbox", "Issuing authority", "the schema, the signing key, the epoch roots, the status",
          ["\\textbf{records, zero-knowledge mode:} an event with no token identifier (C2)",
           "\\textbf{records, online status check:} no who-verified-whom row",
           "\\textbf{cannot:} rebuild the zero-knowledge verification graph from its own database"]),
     210: ("humanbox", "Holder", "the wallet holds a file: token value, signature, issuer key; optionally a stapled status assertion, a membership proof, a presentation code",
          ["\\textbf{sees:} its own credential", "\\textbf{decides:} the disclosure level it presents under",
           "\\textbf{cannot:} upgrade what the server will record (C6)"]),
     330: ("extbox", "Relying party", "runs the detached verifier or an SDK, offline; or calls the issuer as itself",
          ["\\textbf{checks, offline:} authentic; issuer trusted; assertion bound, fresh, ACTIVE; context",
           "\\textbf{learns:} a valid credential exists; the credential value",
           "\\textbf{cannot:} reach the person's record; verify authorization fresher than the assertion"]),
    }
    o = ["% v3-figures/holder-flow.tex: holder, relying party and issuer as a turning triangle.",
         "% The three flows form a cycle, so they are arcs of one circle turning the same way, each",
         "% labelled along its own arc; the stated limitation sits at the centre.",
         "% Generated by tools/figures_en.py.",
         "\\begin{tikzpicture}[",
         "  party/.style={text width=5.1cm, minimum height=5.35cm, align=left, inner sep=5pt, font=\\scriptsize},",
         "]",
         "\\begin{scope}[on background layer]",
         "  \\draw[gold, line width=0.4pt, opacity=0.55] (90:%.2f) -- (210:%.2f) -- (330:%.2f) -- cycle;" % (R, R, R),
         "\\end{scope}"]
    for a, (sty, title, role, rows) in cards.items():
        txt = "white" if sty == "layerbox" else "navydark"
        o.append("\\node[%s, party, text=%s] (p%d) at (%d:%.2f) {{\\bfseries\\small %s}\\\\[1pt]{\\itshape %s}\\\\[4pt]%s};"
                 % (sty, txt, a, a, R, title, role, "\\\\[2pt]".join(rows)))
    flows = [(210, 330, "presents (QR, NFC, file)", "si", "flow"),
             (330, 450, "status check as an organisation; no person named", "si", "flow"),
             (90, 210, "status assertion fetched by possession; no record of who asked", "ti", "flowfaint")]
    GAP = 29
    for a, b, text, style, arrow in flows:
        o.append("\\draw[%s] (%.1f:%.2f) arc[start angle=%.1f, end angle=%.1f, radius=%.2f];" % (arrow, a+GAP, R, a+GAP, b-GAP, R))
        t, _ = arc_label(text, style, ((a + b) / 2) % 360, round(R + 0.38, 3), color="steelgray", lift="-1.5pt")
        o.append(t)
    o.append("\\node[font=\\scriptsize\\bfseries\\color{classmark}, text width=6.2cm, align=center] at (0,0) "
             "{The stated limitation: a full-credential presentation carries a stable \\code{token\\_value}, so two relying "
             "parties can join their logs by it. The login token's subject is no longer that value: since \\code{v9.353} it is "
             "derived per relying party. Unlinkability is issuer-side and scoped to zero-knowledge mode; cross-verifier "
             "unlinkability on a plain presentation is not implemented, by design.};")
    o.append("\\end{tikzpicture}")
    write("holder-flow.tex", o)

# ------------------------------------------------------------------ 9: federation
def federation():
    R = 7.0
    o = [r"""% v3-figures/federation.tex: three authorities on a triangle inscribed in a circle. The sides
% are the trust relations: B attests A, A attests C, and the side between B and C is the
% refused transitive edge. Generated by tools/figures_en.py.
\begin{tikzpicture}[
  auth/.style={layerbox, text width=4.2cm, minimum height=2.35cm, align=center, font=\scriptsize},
]
\begin{scope}[on background layer]""",
         "  \\draw[gold, line width=0.6pt, dash pattern=on 3pt off 2pt] (0,0) circle (%.2f);" % R,
         "\\end{scope}",
         "\\node[auth] (A) at (90:%.2f) {{\\bfseries\\small Authority A}\\\\[2pt]its own database, its own ML-DSA-87 root; publishes manifest, epoch checkpoint, revocation feed};" % R,
         "\\node[auth] (B) at (330:%.2f) {{\\bfseries\\small Authority B}\\\\[2pt]its own database, its own ML-DSA-65 root; publishes the same three objects};" % R,
         "\\node[auth, fill=steelgray!85, draw=steelgray] (C) at (210:%.2f) {{\\bfseries\\small Authority C}\\\\[2pt]trusted by A,\\\\not by B};" % R,
         "\\draw[flow, line width=1.4pt] (B) -- (A);",
         "\\draw[flowfaint] (A) -- (C);",
         "\\draw[refuse, dash pattern=on 4pt off 3pt] (B) -- node[below=3pt, font=\\scriptsize\\bfseries\\color{classmark}, text width=4.4cm, align=center] {no closure: B trusting A never implies B trusts C} (C);",
         "\\path[%s] (90:%.2f) -- (330:%.2f);" % (along("B attests A's key in context 3, until a date", "sc", "navydark", "7pt"), R, R),
         "\\path[%s] (210:%.2f) -- (90:%.2f);" % (along("A attests C, in some context", "si", "steelgray", "7pt"), R, R),
         "\\node[humanbox, text width=3.3cm, align=center, font=\\scriptsize\\bfseries] (h) at (0,1.75) {holder of an A credential};",
         "\\node[extbox, text width=4.3cm, align=center, font=\\scriptsize] (rp) at (0,-1.05) {{\\bfseries relying party that trusts B}\\\\[2pt]decides offline: A's credential is genuine, B's manifest is authentic, fresh and trusted, it attests A's key in context 3, and A's feed does not list the credential};",
         "\\draw[flow] (h) -- node[left=2pt, font=\\tiny\\itshape, text=steelgray] {presents in context 3} (rp);",
         "\\draw[flowfaint] (B.north west) to[out=150, in=0] node[pos=0.3, right=2pt, font=\\tiny\\itshape, text=steelgray, text width=1.4cm, align=left] {fetches B's manifest} (rp.east);",
         "\\node[faint, text width=12.5cm, align=center, anchor=north] at (0,-%.2f) {In CI this runs as two independent instances over HTTP, each with its own database and real key, under a mixed pair of parameter sets. Two instances of one code base, run by one author, prove the protocol; they do not prove institutional independence.};" % (R + 0.35),
         "\\end{tikzpicture}"]
    write("federation.tex", o)

# ------------------------------------------------------------------ 10: transparency
def transparency():
    X1, X2, BUS = 8.2, 12.9, 3.7
    B = {
     "log": "{The log\\\\[-1pt]{\\mdseries\\scriptsize an append-only table of roots (anchor batches, receipt hashes, or anchored timestamps), hashed into a Merkle tree}}",
     "sth": "{Signed tree head\\\\[-1pt]{\\scriptsize log id, tree size, root hash, time; signed by the log's key}}",
     "proofs": "{Proofs\\\\[-1pt]{\\scriptsize consistency: size $m$ is a prefix of size $n$; inclusion: entry $i$ is in the tree}}",
     "mon": "{Monitor\\\\[-1pt]{\\scriptsize anyone runs it; keeps one thing: the last head it accepted. Alerts on a rewrite, a fork, a shrink, a wrong key, time going backwards.}\\\\[2pt]{\\scriptsize\\bfseries\\color{classmark}cannot see whether another observer was shown a different head}}",
     "ledger": "{External ledger\\\\[-1pt]{\\scriptsize an append-only log of heads; returns a receipt with its own head and an inclusion proof (file backend today; chain drivers declared)}}",
     "cosig": "{cosignatures\\\\[-1pt]{\\scriptsize a relying party requires $K$ distinct trusted witnesses on the exact head}}",
     "pool": "{gossip pool\\\\[-1pt]{\\scriptsize each witness posts the head it was shown}}",
     "eq": "{equivocation proof\\\\[-1pt]{\\mdseries\\scriptsize two heads, same size, different roots, both signed by the log: non-repudiable}}",
    }
    note = ("{The protocol for independent witnesses is built and drilled under real signatures. Institutionally "
            "independent witnesses, a bank, a civil-society group, another authority, exist only once the system is "
            "deployed; today the witnesses are three processes in a drill.}")
    o = [r"""% v3-figures/transparency.tex: the log, the monitor, the witnesses, the gossip pool and the
% equivocation proof. Everything the log publishes leaves its signed head along one vertical
% trunk, which branches straight to the monitor, the three witnesses and the external ledger;
% nothing crosses. Generated by tools/figures_en.py.
\begin{tikzpicture}[
  col/.style={minimum width=3.4cm, text width=3.1cm},
  wit/.style={extbox, minimum width=2.6cm, minimum height=0.62cm},
]""",
     "\\node[layerbox, col] (log) at (0,4.3) %s;" % B["log"],
     "\\node[softbox, col] (sth) at (0,0.85) %s;" % B["sth"],
     "\\node[softbox, col] (proofs) at (0,-2.7) %s;" % B["proofs"],
     "\\draw[flow] (log) -- (sth);", "\\draw[flowfaint] (sth) -- (proofs);",
     "\\node[extbox, minimum width=3.6cm, text width=3.3cm] (mon) at (%.2f,4.85) %s;" % (X1, B["mon"]),
     "\\node[wit] (w1) at (%.2f,1.6) {witness 1};" % X1,
     "\\node[wit] (w2) at (%.2f,0.85) {witness 2};" % X1,
     "\\node[wit] (w3) at (%.2f,0.1) {witness 3};" % X1,
     "\\node[extbox, minimum width=3.6cm, text width=3.3cm] (ledger) at (%.2f,-2.95) %s;" % (X1, B["ledger"]),
     "\\draw[flow, -] (sth.east) -- (%.2f,0.85);" % BUS,
     "\\draw[navymid, line width=1pt] (%.2f,4.85) -- (%.2f,-2.95);" % (BUS, BUS),
     "\\draw[flow] (%.2f,4.85) -- (mon.west);" % BUS,
     "\\draw[flow] (%.2f,1.6) -- (w1.west);" % BUS, "\\draw[flow] (%.2f,0.85) -- (w2.west);" % BUS,
     "\\draw[flow] (%.2f,0.1) -- (w3.west);" % BUS, "\\draw[flow] (%.2f,-2.95) -- (ledger.west);" % BUS,
     "\\node[faint, anchor=south, text width=2.6cm, align=center] at (%.2f,4.9) {head + consistency proof};" % ((BUS + X1 - 1.8) / 2),
     "\\node[faint, anchor=south, text width=2.6cm, align=center] at (%.2f,-2.9) {publishes each head};" % ((BUS + X1 - 1.8) / 2),
     "\\node[softbox, minimum width=3.3cm, text width=3.1cm] (cosig) at (%.2f,2.35) %s;" % (X2, B["cosig"]),
     "\\node[softbox, minimum width=3.3cm, text width=3.1cm] (pool) at (%.2f,-0.85) %s;" % (X2, B["pool"]),
     "\\node[corebox, minimum width=3.4cm, text width=3.2cm] (eq) at (%.2f,-4.35) %s;" % (X2, B["eq"]),
     "\\foreach \\w in {w1,w2,w3} { \\draw[flow] (\\w.east) -- (cosig.west); }",
     "\\draw[flowfaint, dash pattern=on 3pt off 2pt] (w3.east) -- (pool.west);",
     "\\draw[flow] (pool) -- (eq);",
     "\\node[faint, text width=15cm, align=center, anchor=north] at (5.60,-6.2) %s;" % note,
     "\\end{tikzpicture}"]
    write("transparency.tex", o)

# ------------------------------------------------------------------ 13: cognition
def cognition():
    R = 6.3
    layers = [(135, "layerbox", "Atlas", "sees what the system is doing: bounded aggregates of events, never a zero-knowledge location", False),
              (45, "layerbox", "Athena", "understands the structure of authority: agencies, keys, contexts, trust, rules, and what enforces each", False),
              (225, "futbox", "Metis", "learns the behaviour of Polaris itself: anomalies, capacity, regressions, release risk", True),
              (315, "futbox", "Myrmex", "attacks Polaris from outside as an independent observer", True)]
    o = [r"""% v3-figures/cognition.tex: the cognitive layers inside the constitution's circle. The
% constitution constrains all four, so it is the circle that encloses them, its words set
% along its rim; the person stands outside, under the red line nothing above may cross.
% Generated by tools/figures_en.py.
\begin{tikzpicture}[
  cog/.style={text width=3.35cm, minimum height=2.8cm, align=center},
]"""]
    o.append("\\draw[gold, line width=1.1pt] (0,0) circle (%.2f);" % R)
    t, _ = arc_label("The constitution constrains them all: the vocation and C1-C10,", "fb", 90, round(R + 0.95, 3), color="navydark", lift="-1.4pt"); o.append(t)
    t, _ = arc_label("enforced in the schema and pinned by invariant checks", "sc", 90, round(R + 0.45, 3), color="navydark", lift="-1.4pt"); o.append(t)
    o.append("\\node[circle, draw=gold, line width=0.8pt, fill=futfill, text width=1.9cm, align=center, inner sep=1pt] (themis) at (0,0) "
             "{{\\bfseries\\small Themis}\\\\{\\tiny a conceptual layer}};")
    for a, sty, name, what, prop in layers:
        tag = "\\\\{\\mdseries\\tiny proposed}" if prop else ""
        o.append("\\node[%s, cog] (l%d) at (%d:4.05) {%s%s\\\\[1pt]{\\mdseries\\scriptsize %s}};" % (sty, a, a, name, tag, what))
        o.append("\\draw[flowfaint] (themis) -- (l%d);" % a)
    Y = R + 1.05
    o.append("\\draw[refuse] (-%.2f,-%.2f) -- (%.2f,-%.2f);" % (R, Y, R, Y))
    o.append("\\node[font=\\scriptsize\\bfseries, text=classmark, text width=12cm, align=center, anchor=south] at (0,-%.2f) "
             "{below this line nothing is modelled: no person node, no subject surrogate, no behavioural profile, no score};" % (Y - 0.05))
    o.append("\\node[humanbox, minimum width=3.2cm, anchor=north] (person) at (0,-%.2f) {a natural person};" % (Y + 0.35))
    o.append("\\node[faint, text width=9cm, anchor=north, align=center] at (person.south) {Atlas and Athena read events and authority "
             "structure; the checks fail the build if a person-level column or traversal appears. Make power legible, not people. "
             "The name Themis is this paper's, not the repository's.};")
    o.append("\\end{tikzpicture}")
    write("cognition.tex", o)

# ------------------------------------------------------------------ 14: senses loop
def senses_loop():
    R = 4.6
    stages = [(90, "layerbox", "Observation", "run the system, not read it"),
              (0, "layerbox", "Failure", "a green check proved the wrong thing"),
              (270, "layerbox", "Model correction", "what the mechanism really proves"),
              (180, "corebox", "New invariant", "a check with a detection test")]
    o = ["% v3-figures/senses-loop.tex: the loop by which an error becomes a sense, as a wheel of",
         "% four stages turning clockwise, with the sense it leaves at the centre.",
         "% Generated by tools/figures_en.py.",
         "\\begin{tikzpicture}[",
         "  stage/.style={text width=3.55cm, minimum height=1.45cm, align=center, font=\\small\\bfseries},",
         "]"]
    for a, sty, title, sub in stages:
        o.append("\\node[%s, stage] (s%d) at (%d:%.2f) {%s\\\\[-1pt]{\\mdseries\\scriptsize %s}};" % (sty, a, a, R, title, sub))
    order = [90, 0, 270, 180]; GAP = 24
    for i, a in enumerate(order):
        b = order[(i + 1) % 4]
        start, end = a - GAP, (b + GAP) if b < a else (b + GAP - 360)
        o.append("\\draw[flow, line width=1.2pt] (%.1f:%.2f) arc[start angle=%.1f, end angle=%.1f, radius=%.2f];" % (start, R, start, end, R))
    o.append("\\node[softbox, text width=4.6cm, align=center, font=\\scriptsize] at (0,0) {\\textbf{A permanent new sense:} "
             "the failure class cannot recur unseen. Continuous integration carries it on every push.};")
    t, _ = arc_label("the loop runs again on the next observation; the invariants accumulate, they are never deleted",
                     "si", 270, 6.55, color="steelgray", lift="-1.5pt")
    o.append(t)
    o.append("\\end{tikzpicture}")
    write("senses-loop.tex", o)

# ------------------------------------------------------------------ 16: stigmergy
def stigmergy():
    R = 4.9
    agents = ["scout", "trust boundary", "cryptographic", "privacy", "refutation", "protocol", "concurrency", "state transition"]
    o = [r"""% v3-figures/stigmergy.tex: the proposed colony as an octagon: eight specialised agents round
% the evidence landscape they mark, the orchestrator above, and below it the only road to
% confidence. Mirror-symmetric about the vertical axis. Generated by tools/figures_en.py.
\begin{tikzpicture}[
  agent/.style={futbox, text width=2.5cm, minimum height=1.0cm, align=center, font=\scriptsize},
]
\begin{scope}[on background layer]"""]
    o.append("  \\draw[gold, line width=0.5pt, opacity=0.6] " + " -- ".join("(%.1f:%.2f)" % (22.5 + 45*k, R) for k in range(8)) + " -- cycle;")
    o.append("  \\draw[gold, line width=0.4pt, opacity=0.35, dash pattern=on 2pt off 2pt] (0,0) circle (%.2f);" % (R - 1.55))
    o.append("\\end{scope}")
    o.append("\\node[futbox, circle, text width=3.6cm, align=center, font=\\scriptsize, inner sep=3pt] (land) at (0,0) "
             "{\\textbf{Evidence landscape}\\\\{\\tiny persistent, machine-readable}\\\\[2pt]{\\tiny pheromones: suspicion, "
             "trust-boundary anomalies, odd state transitions, cryptographic assumptions, missing edges; they strengthen under "
             "independent evidence and decay unsupported}};")
    for k, name in enumerate(agents):
        o.append("\\node[agent] (a%d) at (%.1f:%.2f) {%s};" % (k, 22.5 + 45*k, R, name))
        o.append("\\draw[flowfut, <->] (a%d) -- (land);" % k)
    o.append("\\node[futbox, text width=3.3cm, align=center, font=\\scriptsize] (queen) at (0,%.2f) {\\textbf{orchestrator}\\\\allocates work, aggregates evidence, decides nothing};" % (R + 1.9))
    o.append("\\draw[flowfut, <->] (queen.south) -- ++(0,-0.9);")
    o.append("\\node[extbox, text width=7.2cm, align=center, font=\\scriptsize] (ext) at (0,-%.2f) {Confidence comes only from "
             "external evidence: a failing test, a runtime trace, a fuzz case, a static finding, a formal counterexample, an "
             "independent reproduction. \\textbf{Agreement between models is not evidence.}};" % (R + 2.05))
    o.append("\\draw[flow] (ext.north) -- (land.south);")
    o.append("\\node[corebox, text width=4.2cm, align=center] (pol) at (0,-%.2f) {Polaris\\\\[-1pt]{\\mdseries\\scriptsize reproducible failure, test, invariant, new sense}};" % (R + 4.85))
    o.append("\\draw[flow] (ext) -- node[right=3pt, font=\\tiny\\itshape, text=steelgray] {reproduced} (pol);")
    o.append("\\end{tikzpicture}")
    write("stigmergy.tex", o)

if __name__ == "__main__":
    for f in (core_to_shell, town_map, outside_witnesses, holder_flow, federation, transparency, cognition, senses_loop, stigmergy):
        f()
