"""make_fixtures.py -- regenerate the SDKs' shared test fixtures under real ML-DSA-65.

Each fixture is an input no conformance vector covers, found by a held-out round of
semantic mutations on 2026-09-23: a mutation that survived every instrument names an input
nothing exercised, and the fixture is that input. Both SDK suites read the same file, so the
two published reference SDKs are held to one answer.

    python3 sdk/testdata/make_fixtures.py        # needs liboqs-python

Keys are fresh on every run and thrown away; only public keys and signatures are written.
The fixtures are signed statements in the wire format, not test doubles: a verifier that
accepts them is doing the same work it does on a real feed.
"""
import hashlib
import json
import pathlib

import oqs

HERE = pathlib.Path(__file__).resolve().parent
ALG = "ML-DSA-65"
FEED_KEYS = ["format", "authority", "epoch_number", "as_of", "revoked_root_hex", "revoked_count",
             "revoked_leaves", "issued_at", "expires_at", "algorithm"]
MANIFEST_KEYS = ["format", "authority", "anchors", "attestations", "epoch", "revocation",
                 "issued_at", "expires_at", "algorithm"]


def _canonical(obj, keys):
    return json.dumps({k: obj.get(k) for k in keys}, sort_keys=True, separators=(",", ":")).encode()


def _signer():
    s = oqs.Signature(ALG)
    return s, s.generate_keypair().hex()


def _sign_statement(signer, pk_hex, obj, keys):
    obj["signature_hex"] = signer.sign(hashlib.sha3_256(_canonical(obj, keys)).digest()).hex()
    obj["public_key_hex"] = pk_hex
    return obj


def revocation_uppercase_leaf():
    """A cross-authority presentation whose issuer's own, genuinely signed revocation feed
    lists the credential's leaf in UPPER-case hex. The feed's commitment is computed over
    lowercased leaves (wire spec), so the feed is authentic; a membership test that compares
    case-sensitively misses the listing and accepts a revoked credential."""
    issuer, issuer_pk = _signer()
    authority, authority_pk = _signer()
    token = "HELD-OUT-UPPERCASE-LEAF-0001"
    pack = {"format": "polaris-authenticity-pack/1", "algorithm": ALG, "token_value": token,
            "signature_hex": issuer.sign(hashlib.sha3_256(token.encode()).digest()).hex(),
            "public_key_hex": issuer_pk}
    manifest = _sign_statement(authority, authority_pk, {
        "format": "polaris-federation-manifest/1", "algorithm": ALG,
        "authority": {"agency_id": "B", "name": "Authority B"},
        "anchors": [{"public_key_hex": authority_pk, "status": "active"}],
        "attestations": [{"attested_public_key_hex": issuer_pk, "context_id": 1}],
        "epoch": {"number": 1, "root_hex": "bb" * 16}, "revocation": {"as_of": "2026-01-01T00:00:00Z"},
        "issued_at": "2026-01-01T00:00:00Z", "expires_at": "2027-01-01T00:00:00Z"}, MANIFEST_KEYS)
    leaf = hashlib.sha3_256(token.encode()).hexdigest()
    feed = _sign_statement(issuer, issuer_pk, {
        "format": "polaris-revocation-feed/1", "algorithm": ALG,
        "authority": {"agency_id": "A", "name": "Authority A"}, "epoch_number": 1,
        "as_of": "2026-01-01T00:00:00Z",
        "revoked_root_hex": hashlib.sha3_256(leaf.encode()).hexdigest(),
        "revoked_count": 1, "revoked_leaves": [leaf.upper()],
        "issued_at": "2026-01-01T00:00:00Z", "expires_at": "2027-01-01T00:00:00Z"}, FEED_KEYS)
    return {"_fixture": {"name": "revocation-uppercase-leaf", "provenance":
                         "real ML-DSA-65 (liboqs), regenerated by sdk/testdata/make_fixtures.py",
                         "now": "2026-05-01T00:00:00Z", "context_id": 1,
                         "expect": "reject: credential is revoked"},
            "pack": pack, "manifest": manifest, "feed": feed}


if __name__ == "__main__":
    out = HERE / "revocation-uppercase-leaf.json"
    out.write_text(json.dumps(revocation_uppercase_leaf(), indent=2, sort_keys=True) + "\n")
    print("wrote", out.relative_to(HERE.parent.parent))
