"""make_fixtures.py -- regenerate the SDKs' shared test fixtures under real ML-DSA-65.

Each fixture is an input no conformance vector covers, found by a held-out round of
semantic mutations on 2026-09-23: a mutation that survived every instrument names an input
nothing exercised, and the fixture is that input. Both SDK suites read the same file, so the
two published reference SDKs are held to one answer.

    python3 sdk/testdata/make_fixtures.py        # needs liboqs-python

Keys are fresh on every run and thrown away; only public keys and signatures are written.
The fixtures are signed statements in the wire format, not test doubles: a verifier that
accepts them is doing the same work it does on a real feed.
"""
import hashlib
import json
import pathlib

import oqs

HERE = pathlib.Path(__file__).resolve().parent
ALG = "ML-DSA-65"
FEED_KEYS = ["format", "authority", "epoch_number", "as_of", "revoked_root_hex", "revoked_count",
             "revoked_leaves", "issued_at", "expires_at", "algorithm"]
MANIFEST_KEYS = ["format", "authority", "anchors", "attestations", "epoch", "revocation",
                 "issued_at", "expires_at", "algorithm"]


def _canonical(obj, keys):
    return json.dumps({k: obj.get(k) for k in keys}, sort_keys=True, separators=(",", ":")).encode()


def _signer():
    s = oqs.Signature(ALG)
    return s, s.generate_keypair().hex()


def _sign_statement(signer, pk_hex, obj, keys):
    obj["signature_hex"] = signer.sign(hashlib.sha3_256(_canonical(obj, keys)).digest()).hex()
    obj["public_key_hex"] = pk_hex
    return obj


def revocation_uppercase_leaf():
    """A cross-authority presentation whose issuer's own, genuinely signed revocation feed
    lists the credential's leaf in UPPER-case hex. The feed's commitment is computed over
    lowercased leaves (wire spec), so the feed is authentic; a membership test that compares
    case-sensitively misses the listing and accepts a revoked credential."""
    issuer, issuer_pk = _signer()
    authority, authority_pk = _signer()
    token = "HELD-OUT-UPPERCASE-LEAF-0001"
    pack = {"format": "polaris-authenticity-pack/1", "algorithm": ALG, "token_value": token,
            "signature_hex": issuer.sign(hashlib.sha3_256(token.encode()).digest()).hex(),
            "public_key_hex": issuer_pk}
    manifest = _sign_statement(authority, authority_pk, {
        "format": "polaris-federation-manifest/1", "algorithm": ALG,
        "authority": {"agency_id": "B", "name": "Authority B"},
        "anchors": [{"public_key_hex": authority_pk, "status": "active"}],
        "attestations": [{"attested_public_key_hex": issuer_pk, "context_id": 1}],
        "epoch": {"number": 1, "root_hex": "bb" * 16}, "revocation": {"as_of": "2026-01-01T00:00:00Z"},
        "issued_at": "2026-01-01T00:00:00Z", "expires_at": "2027-01-01T00:00:00Z"}, MANIFEST_KEYS)
    leaf = hashlib.sha3_256(token.encode()).hexdigest()
    feed = _sign_statement(issuer, issuer_pk, {
        "format": "polaris-revocation-feed/1", "algorithm": ALG,
        "authority": {"agency_id": "A", "name": "Authority A"}, "epoch_number": 1,
        "as_of": "2026-01-01T00:00:00Z",
        "revoked_root_hex": hashlib.sha3_256(leaf.encode()).hexdigest(),
        "revoked_count": 1, "revoked_leaves": [leaf.upper()],
        "issued_at": "2026-01-01T00:00:00Z", "expires_at": "2027-01-01T00:00:00Z"}, FEED_KEYS)
    return {"_fixture": {"name": "revocation-uppercase-leaf", "provenance":
                         "real ML-DSA-65 (liboqs), regenerated by sdk/testdata/make_fixtures.py",
                         "now": "2026-05-01T00:00:00Z", "context_id": 1,
                         "expect": "reject: credential is revoked"},
            "pack": pack, "manifest": manifest, "feed": feed}


BINDING_KEYS = ["format", "token_value", "holder_public_key_hex", "holder_algorithm", "bound_at",
                "status", "issued_at", "expires_at", "algorithm"]
PROOF_KEYS = ["format", "token_value", "context_id", "verifier_nonce", "issued_at", "algorithm"]


def holder_chain_early_binding():
    """A genuine holder chain whose binding was issued a DAY before the proof. The published
    conformance chain issues both at the same instant, so a proof dated inside the one-minute
    skew is also before its binding's window opens, and the skew bound cannot be told apart
    from the binding's freshness: a mutation doubling the skew survived both SDKs. Here the
    binding is valid throughout, so only the proof's own window decides."""
    issuer, issuer_pk = _signer()
    holder, holder_pk = _signer()
    token = "HELD-OUT-HOLDER-0001"
    credential = {"format": "polaris-authenticity-pack/1", "algorithm": ALG, "token_value": token,
                  "signature_hex": issuer.sign(hashlib.sha3_256(token.encode()).digest()).hex(),
                  "public_key_hex": issuer_pk}
    binding = _sign_statement(issuer, issuer_pk, {
        "format": "polaris-holder-binding/1", "algorithm": ALG, "token_value": token,
        "holder_public_key_hex": holder_pk, "holder_algorithm": ALG,
        "bound_at": "2026-04-29T00:00:00Z", "status": "active",
        "issued_at": "2026-04-30T00:00:00Z", "expires_at": "2026-05-02T00:00:00Z"}, BINDING_KEYS)
    proof = _sign_statement(holder, holder_pk, {
        "format": "polaris-holder-proof/1", "algorithm": ALG, "token_value": token,
        "context_id": 1, "verifier_nonce": "held-out-nonce", "issued_at": "2026-05-01T00:00:00Z"},
        PROOF_KEYS)
    return {"_fixture": {"name": "holder-chain-early-binding", "provenance":
                         "real ML-DSA-65 (liboqs), regenerated by sdk/testdata/make_fixtures.py",
                         "nonce": "held-out-nonce", "context_id": 1,
                         "proof_issued_at": "2026-05-01T00:00:00Z"},
            "credential": credential, "binding": binding, "proof": proof}


def federation_variants():
    """One genuine cross-authority setup and its variants, each differing from the base in ONE
    property, for the SDKs' verify_cross_authority. 2026-09-23: a held-out round removed ten of
    its rules and eight survived: a stale manifest, a retired anchor, an attestation of another
    key, a badly signed attestation, require_signed_attestation, and a revocation feed that is
    stale, by another issuer, or not authentic were each accepted with every test green."""
    issuer, issuer_pk = _signer()
    authority, authority_pk = _signer()
    retired, retired_pk = _signer()
    stranger, stranger_pk = _signer()
    token = "HELD-OUT-FEDERATION-0001"
    pack = {"format": "polaris-authenticity-pack/1", "algorithm": ALG, "token_value": token,
            "signature_hex": issuer.sign(hashlib.sha3_256(token.encode()).digest()).hex(),
            "public_key_hex": issuer_pk}

    def manifest(expires="2027-01-01T00:00:00Z", attested=issuer_pk, attestation_extra=None):
        att = {"attested_public_key_hex": attested, "context_id": 1}
        att.update(attestation_extra or {})
        return _sign_statement(authority, authority_pk, {
            "format": "polaris-federation-manifest/1", "algorithm": ALG,
            "authority": {"agency_id": "B", "name": "Authority B"},
            "anchors": [{"public_key_hex": authority_pk, "status": "active"},
                        {"public_key_hex": retired_pk, "status": "retired"}],
            "attestations": [att], "epoch": {"number": 1, "root_hex": "bb" * 16},
            "revocation": {"as_of": "2026-01-01T00:00:00Z"},
            "issued_at": "2026-01-01T00:00:00Z", "expires_at": expires}, MANIFEST_KEYS)

    def feed(signer=issuer, signer_pk=issuer_pk, expires="2027-01-01T00:00:00Z"):
        return _sign_statement(signer, signer_pk, {
            "format": "polaris-revocation-feed/1", "algorithm": ALG,
            "authority": {"agency_id": "A", "name": "Authority A"}, "epoch_number": 1,
            "as_of": "2026-01-01T00:00:00Z", "revoked_root_hex": hashlib.sha3_256(b"").hexdigest(),
            "revoked_count": 0, "revoked_leaves": [],
            "issued_at": "2026-01-01T00:00:00Z", "expires_at": expires}, FEED_KEYS)

    bad = feed()
    bad["signature_hex"] = ("0" if bad["signature_hex"][0] != "0" else "1") + bad["signature_hex"][1:]
    return {"_fixture": {"name": "federation-variants", "provenance":
                         "real ML-DSA-65 (liboqs), regenerated by sdk/testdata/make_fixtures.py",
                         "now": "2026-07-01T00:00:00Z", "context_id": 1,
                         "note": "short-lived variants expire 2026-06-01, before `now`"},
            "pack": pack, "trusted_anchor": authority_pk, "retired_anchor": retired_pk,
            "manifests": {"base": manifest(), "stale": manifest(expires="2026-06-01T00:00:00Z"),
                          "other_key": manifest(attested=stranger_pk),
                          "bad_attestation_signature": manifest(attestation_extra={
                              "public_key_hex": authority_pk, "signature_hex": "00" * 3309})},
            "feeds": {"clean": feed(), "stale": feed(expires="2026-06-01T00:00:00Z"),
                      "other_issuer": feed(stranger, stranger_pk), "not_authentic": bad}}


STH_KEYS = ["format", "log_id", "tree_size", "root_hash_hex", "timestamp"]
COSIG_KEYS = ["format", "log_id", "tree_size", "root_hash_hex"]
LOG_ID = "polaris-timestamp-log"


def anchor_variants():
    """A genuinely signed one-entry timestamp log over the published conformance timestamp, and
    variants that differ in one signed property: a head for another log, and cosignatures over
    another tree size or another root. verify_timestamp_anchor never checks the timestamp's own
    signature, only its hash, so the published timestamp is reused as the entry. 2026-09-23:
    those three rules survived a held-out round, and the TypeScript SDK cannot replace a
    signature verdict in a test, so they need real signatures to be tested at all."""
    import sys
    sys.path.insert(0, str(HERE.parent / "python"))
    import polaris_verify as pv
    ts = json.loads((HERE.parent.parent / "conformance" / "vectors" / "timestamp-valid.json").read_text())
    ts.pop("anchor", None)
    entry = pv.timestamp_hash(ts)
    root = pv._leaf_hash(entry).hex()
    log, log_pk = _signer()
    w1, w1_pk = _signer()
    w2, w2_pk = _signer()

    def sth(log_id=LOG_ID):
        return _sign_statement(log, log_pk, {"format": "polaris-transparency-sth/1", "algorithm": ALG,
                                             "log_id": log_id, "tree_size": 1, "root_hash_hex": root,
                                             "timestamp": "2026-05-01T00:00:10Z"}, STH_KEYS)

    def cosig(signer, pk, tree_size=1, root_hex=root):
        return _sign_statement(signer, pk, {"format": "polaris-transparency-cosignature/1", "algorithm": ALG,
                                            "log_id": LOG_ID, "tree_size": tree_size,
                                            "root_hash_hex": root_hex}, COSIG_KEYS)

    def anchored(head, cosignatures):
        out = dict(ts)
        out["anchor"] = {"log_id": head["log_id"], "timestamp_hash": entry, "sth": head,
                         "proof": {"log_id": LOG_ID, "entry_hex": entry, "index": 0, "tree_size": 1,
                                   "root_hash_hex": root, "proof_hex": []},
                         "cosignatures": cosignatures}
        return out

    good = [cosig(w1, w1_pk), cosig(w2, w2_pk)]
    return {"_fixture": {"name": "anchor-variants", "provenance":
                         "real ML-DSA-65 (liboqs), regenerated by sdk/testdata/make_fixtures.py"},
            "log_key": log_pk, "witnesses": [w1_pk, w2_pk],
            "base": anchored(sth(), good),
            "other_log": anchored(sth("some-other-log"), good),
            "cosig_other_size": anchored(sth(), [good[0], cosig(w2, w2_pk, tree_size=2)]),
            "cosig_other_root": anchored(sth(), [good[0], cosig(w2, w2_pk, root_hex="00" * 32)])}


if __name__ == "__main__":
    for name, build in (("revocation-uppercase-leaf.json", revocation_uppercase_leaf),
                        ("holder-chain-early-binding.json", holder_chain_early_binding),
                        ("federation-variants.json", federation_variants),
                        ("anchor-variants.json", anchor_variants)):
        out = HERE / name
        if out.exists() and "--all" not in __import__("sys").argv:
            print("kept", out.relative_to(HERE.parent.parent), "(pass --all to regenerate)")
            continue
        out.write_text(json.dumps(build(), indent=2, sort_keys=True) + "\n")
        print("wrote", out.relative_to(HERE.parent.parent))
