"""ru-glossary.py -- the Latin-to-Russian map for the Russian edition of the v3 report.

The Russian edition renders EVERY identifier in Russian, not only the prose: table
names, check names, column names, enum values, paths, package names and standard
designations. The repository itself uses the Latin forms on the left. This file is
the single place the correspondence is written down, so that the edition is
reproducible and a reader who needs the original name can find it.

Order matters: the applier sorts by length descending, so ML-DSA-65 is replaced
before ML-DSA and check_transparency_log before check_transparency.

Deliberately NOT translated:
  * the motto, Fixus inter mutabilia, which is Latin and not English;
  * commit hashes, which are base-16 numerals rather than words.
"""

ENTITIES = {
    "IdentityToken": "ТокенЛичности",
    "TokenSignature": "ПодписьТокена",
    "TokenPermission": "РазрешениеТокена",
    "TokenLifecycleEvent": "СобытиеЦиклаТокена",
    "TokenStateEpochLeaf": "ЛистЭпохиТокенов",
    "TokenStateEpoch": "ЭпохаТокенов",
    "Individual": "ФизическоеЛицо",
    "IndividualErasureEvent": "СобытиеСтиранияЛица",
    "AgencyAlgorithmAuth": "ДопускКАлгоритму",
    "AgencyTrustAttestation": "АттестацияДоверия",
    "AgencyQuota": "КвотаВедомства",
    "AgencyEvent": "СобытиеВедомства",
    "Agency": "Ведомство",
    "CryptographicAlgorithm": "КриптоАлгоритм",
    "VerificationContext": "КонтекстПроверки",
    "VerificationEvent": "СобытиеПроверки",
    "AuthorityKeyEvent": "СобытиеКлючаОргана",
    "IssuerDiscretionPolicy": "ПолитикаУсмотрения",
    "RelyingPartyEvent": "СобытиеСтороны",
    "RelyingParty": "ДоверяющаяСторона",
    "AuthCodeConsumed": "КодВходаПоглощён",
    "ExchangeNonce": "ЧислоОбмена",
    "ExchangeReceiptLog": "ЖурналРасписок",
    "AppUserEvent": "СобытиеПользователя",
    "AppUser": "ПользовательПриложения",
    "EnrollmentProofing": "ПодтверждениеРегистрации",
    "EnrollmentEvidence": "ОснованияРегистрации",
    "EnrollmentStatusEvent": "СостояниеРегистрации",
    "EnrollmentCode": "КодРегистрации",
    "RefereeVouching": "Поручительство",
    "DeviceBinding": "ПривязкаУстройства",
    "RevocationList": "СписокОтзывов",
    "RecoveryRequest": "ЗапросВосстановления",
    "DuressEvent": "СобытиеПринуждения",
    "ZkVerificationNonce": "ЧислоДоказательства",
    "BlockchainAnchor": "ЯкорьЦепиБлоков",
    "HolderKeyEvent": "СобытиеКлючаДержателя",
    "CardPersonalization": "ПерсонализацияКарты",
    "AnchorBatch": "ПакетЯкорей",
    "TimestampLog": "ЖурналОтметокВремени",
    "AuthAuditLog": "ЖурналВходов",
    "AuditAccessLog": "ЖурналДоступаАудита",
    "LifecycleArchiveCheckpoint": "КонтрольнаяТочкаАрхива",
    "RetentionPolicy": "ПолитикаХранения",
    "BulkEnrollmentBatch": "ПакетРегистраций",
    "schema_version": "ВерсияСхемы",
    "OperatorSession": "СессияОператора",
    "OperatorWebauthnCredential": "АппаратныйКлючОператора",
    "athena_constitutional_rule": "афина_основное_правило",
    "athena_key_custody": "афина_хранение_ключей",
    "athena_rule_enforcement": "афина_исполнение_правил",
    "BulkEnrollmentStaging": "БуферРегистраций",
}

CHECKS = {
    "check_algorithm_agility": "проверка_алгоритмическая_гибкость",
    "check_aor_append_only_triggers": "проверка_асз_триггеры_добавления",
    "check_aor_privilege_boundary": "проверка_асз_граница_привилегий",
    "check_append_only_tables_are_tested_exhaustively": "проверка_таблицы_добавления_проверены_исчерпывающе",
    "check_athena_no_person": "проверка_афина_без_человека",
    "check_attacks_run": "проверка_атаки_выполняются",
    "check_audited_reads_are_logged": "проверка_поднадзорные_чтения_записываются",
    "check_auth_broker": "проверка_брокер_входа",
    "check_broker_policy_bound": "проверка_политика_брокера_связана",
    "check_c1c10_objects_resolve": "проверка_объекты_с1с10_разрешаются",
    "check_c6_atlas_redacts_zk_location": "проверка_с6_атлас_скрывает_местоположение_нр",
    "check_card_emulator": "проверка_эмулятор_карты",
    "check_card_profile": "проверка_профиль_карты",
    "check_conformance_asks_the_relying_party_question": "проверка_соответствие_задаёт_вопрос_доверяющей_стороны",
    "check_conformance_suite": "проверка_набор_соответствия",
    "check_constraint_suite_is_mutation_tested": "проверка_набор_ограничений_проверен_мутацией",
    "check_cross_authority_zk": "проверка_межведомственное_нр",
    "check_detached_verifier": "проверка_отделяемый_верификатор",
    "check_document_signing": "проверка_подписание_документов",
    "check_documented_verifier_commands_run": "проверка_описанные_команды_верификатора_выполняются",
    "check_duress_claims_are_aware": "проверка_утверждения_о_принуждении_осведомлённые",
    "check_duress_on_card": "проверка_принуждение_на_карте",
    "check_epoch_revocation_propagation": "проверка_распространение_отзывов_по_эпохам",
    "check_exchange_gateway": "проверка_шлюз_обмена",
    "check_exchange_receipt": "проверка_расписка_обмена",
    "check_exchange_trust_directional": "проверка_доверие_обмена_направленное",
    "check_federation_status_bundle": "проверка_сводный_набор_состояний_федерации",
    "check_federation_topology": "проверка_топология_федерации",
    "check_federation_two_instances": "проверка_федерация_два_экземпляра",
    "check_holder_verifier_flow": "проверка_поток_держатель_верификатор",
    "check_holder_wallet": "проверка_кошелёк_держателя",
    "check_inter_authority_protocol": "проверка_межведомственный_протокол",
    "check_ltv_timestamp_trust": "проверка_доверие_отметке_времени_для_долгосрочности",
    "check_no_fk_cascade": "проверка_нет_каскада_внешних_ключей",
    "check_offline_verification": "проверка_автономная_проверка",
    "check_oid4vp_verifier_boundary": "проверка_граница_верификатора_оид4вп",
    "check_pairwise_presentation": "проверка_попарное_предъявление",
    "check_post_quantum_claims_are_agility": "проверка_постквантовые_утверждения_есть_гибкость",
    "check_pqc_second_witness": "проверка_пкк_второй_свидетель",
    "check_pqc_signing_wired": "проверка_пкк_подписание_подключено",
    "check_procedure_refusals_are_mutation_tested": "проверка_отказы_процедур_проверены_мутацией",
    "check_protocol_versioning": "проверка_версионирование_протокола",
    "check_qr_resource_bounds": "проверка_ресурсные_границы_куар",
    "check_quantum_event_readiness": "проверка_готовность_к_квантовому_событию",
    "check_real_pqc_default_boot": "проверка_настоящая_пкк_при_запуске_по_умолчанию",
    "check_redaction_adversary_is_not_flattered": "проверка_противнику_сокрытия_не_льстят",
    "check_registry": "проверка_реестр",
    "check_relying_party_api": "проверка_ппи_доверяющей_стороны",
    "check_retention_engine": "проверка_механизм_хранения",
    "check_route_guards_are_derived_not_listed": "проверка_стражи_маршрутов_выводятся_а_не_перечисляются",
    "check_scoped_nullifier": "проверка_нуллификатор_с_областью",
    "check_sdk_refusals_are_mutation_tested": "проверка_отказы_сдк_проверены_мутацией",
    "check_seed_restart_resets_dependent_records": "проверка_перезапуск_посева_обнуляет_зависимые_записи",
    "check_status_distribution": "проверка_раздача_состояний",
    "check_timestamp_authority": "проверка_служба_отметок_времени",
    "check_timestamp_transparency": "проверка_прозрачность_отметок_времени",
    "check_transparency_gossip": "проверка_обмен_слухами_прозрачности",
    "check_transparency_log": "проверка_журнал_прозрачности",
    "check_transparency_program": "проверка_программа_прозрачности",
    "check_transparency_publication": "проверка_публикация_прозрачности",
    "check_triggers_are_mutation_tested": "проверка_триггеры_проверены_мутацией",
    "check_trust_lifecycle": "проверка_жизненный_цикл_доверия",
    "check_typescript_sdk": "проверка_сдк_тайпскрипт",
    "check_unique_rules_are_tested_exhaustively": "проверка_уникальные_правила_проверены_исчерпывающе",
    "check_verifier_device": "проверка_устройство_проверки",
    "check_verifier_fuzz": "проверка_фаззинг_верификатора",
    "check_verify_witness_sampling": "проверка_выборка_свидетелей_при_проверке",
    "check_wallet_presentation": "проверка_предъявление_кошелька",
    "check_wire_spec_matches_code": "проверка_спецификация_передачи_совпадает_с_кодом",
    "check_ha_automation": "проверка_автоматика_отказоустойчивости",
    "check_multi_region_dr": "проверка_восстановление_между_регионами",
    "check_read_replica_routing": "проверка_маршрутизация_реплик",
    "check_event_table_partitioning": "проверка_разбиение_таблиц_событий",
    "check_dr_drill_scheduled": "проверка_учение_восстановления_по_расписанию",
    "check_chaos_program": "проверка_программа_хаоса",
    "check_zero_downtime_deploy": "проверка_выпуск_без_простоя",
    "check_capacity_model": "проверка_модель_ёмкости",
    "check_abuse_controls": "проверка_защита_от_злоупотреблений",
    "check_every_audit_event_has_a_writer": "проверка_у_каждого_события_аудита_есть_писатель",
    "check_logs_exclude_pii": "проверка_журналы_без_личных_данных",
    "check_container_hardening": "проверка_укрепление_контейнеров",
    "check_cve_scanning": "проверка_поиск_уязвимостей",
    "check_drills_count_their_cases": "проверка_учения_считают_случаи",
    "check_coexistence_plan": "проверка_план_сосуществования",
    "check_athena_read_only": "проверка_афина_только_чтение",
    "check_athena_functions_bounded": "проверка_функции_афины_ограничены",
    "check_athena_non_sovereign": "проверка_афина_не_распоряжается",
    "check_athena_rule_enforcement_resolves": "проверка_исполнение_правил_афины_разрешается",
    "check_atlas_console": "проверка_консоль_атласа",
    "check_benchmark_measures_growth": "проверка_замер_измеряет_рост",
    "check_verify_enforced": "проверка_проверка_подписи_обязательна",
    "signatures_cryptographically_verify": "подписи_проверяются_криптографически",
    "check_national_simulation": "проверка_национальное_моделирование",
    "check_ship_tool": "проверка_инструмент_выпуска",
    "check_internal_kex_measured": "проверка_внутренний_обмен_ключами_измерен",
    "check_detection_tests_have_a_positive_control": "проверка_у_тестов_обнаружения_есть_положительный_контроль",
    "check_csrf_exemptions_do_not_trust_the_session": "проверка_исключения_мпз_не_доверяют_сессии",
    "check_advisory_locks_have_a_contention_test": "проверка_у_рекомендательных_блокировок_есть_тест_соперничества",
    "check_roadmap_consistent": "проверка_дорожная_карта_согласована",
    "check_key_custody_abstraction": "проверка_абстракция_хранения_ключей",
    "check_zk_tree_depth_synced": "проверка_глубина_дерева_нр_согласована",
    "check_holder_side_prover": "проверка_доказыватель_на_стороне_держателя",
    "check_enrollment_code": "проверка_регистрационный_код",
    "check_trusted_referee": "проверка_доверенный_поручитель",
    "check_edge_pq_kex": "проверка_пк_обмен_ключами_на_кромке",
    "check_session_origin_hardening": "проверка_укрепление_сессий_и_источника",
    "check_duress_alertable": "проверка_оповещение_о_принуждении",
    "check_holder_key_binding": "проверка_привязка_ключа_держателя",
    "check_agent_grant": "проверка_полномочие_агента",
    "check_zk_witnesses_are_mutation_tested": "проверка_свидетели_нр_проверены_мутацией",
}

# Database objects, columns, enum values, SQL keywords.
CODE = {
    "individual_id": "физ_лицо_ид",
    "token_id": "токен_ид",
    "uq_one_active_per_person": "ун_один_действующий_на_человека",
    "chk_disclosure_token_consistency": "пр_согласованность_раскрытия_и_токена",
    "trg_token_state_machine": "тр_автомат_состояний_токена",
    "reject_audit_modification": "отвергнуть_изменение_аудита",
    "verify_signed_document": "проверить_подписанный_документ",
    "insufficient_privilege": "недостаточно_привилегий",
    "currently_authoritative": "полномочно_сейчас",
    "result: PASSED": "результат: ПРОЙДЕНО",
    "cryptography": "криптография",
    "authenticate": "опознать",
    "family_name": "фамилия",
    "given_name": "имя",
    "algorithm": "алгоритм",
    "audience": "аудитория",
    "authentic": "подлинно",
    "expired": "просрочено",
    "decision": "решение",
    "exports": "экспорты",
    "bounded": "ограничено",
    "exposed": "открыто",
    "claims": "утверждения",
    "usable": "пригодно",
    "status": "состояние",
    "reject": "отвергнуть",
    "nonce": "одноразовое_число",
    "verify": "проверка",
    "crypto": "крипто",
    "false": "ложь",
    "true": "истина",
    "auto": "авто",
    "cnf": "пк",
    "iat": "выдан",
    "iss": "эмитент",
    "vct": "тип_уд",
    "deprecation_date": "дата_устаревания",
    "issuer_signature": "подпись_эмитента",
    "token_value": "значение_токена",
    "expires_at": "истекает_в",
    "issued_at": "выдано_в",
    "max_window": "макс_окно",
    "max_age": "макс_возраст",
    "max-age": "макс-возраст",
    "no-store": "не-хранить",
    "script-src 'self'": "скрипт-источник 'свой'",
    "digitalSignature": "цифроваяПодпись",
    "direct_post.jwt": "прямая_отправка.джвт",
    "kb_signature": "пк_подпись",
    "kb_freshness": "пк_свежесть",
    "sd_hash": "ир_хеш",
    "as_of": "по_состоянию_на",
    "node_modules": "модули_ноде",
    "uc1_issue": "сц1_выдача",
    "polaris_app": "полярис_прил",
    "POLARIS_*": "ПОЛЯРИС_*",
    "ZERO_KNOWLEDGE": "НУЛЕВОЕ_РАЗГЛАШЕНИЕ",
    "SELECTIVE": "ИЗБИРАТЕЛЬНОЕ",
    "DETERMINISTIC-PLACEHOLDER-SHA3-256": "ДЕТЕРМИНИРОВАННАЯ-ЗАГЛУШКА-ША3-256",
    "NO ACTION": "БЕЗ ДЕЙСТВИЯ",
    "RETURNING": "ВОЗВРАЩАЯ",
    "DEACTIVATED": "ДЕАКТИВИРОВАН",
    "ACTIVATED": "АКТИВИРОВАН",
    "REVOKED": "ОТОЗВАН",
    "DORMANT": "СПЯЩИЙ",
    "RESERVE": "РЕЗЕРВ",
    "EXPIRED": "ИСТЁК",
    "ISSUED": "ВЫДАН",
    "ACTIVE": "ДЕЙСТВУЮЩИЙ",
    "EXEMPT": "ОСВОБОЖДЁН",
    "PASSED": "ПРОЙДЕНО",
    "REVIEW": "НА РАССМОТРЕНИИ",
    "SELECT": "ВЫБРАТЬ",
    "UPDATE": "ОБНОВИТЬ",
    "DELETE": "УДАЛИТЬ",
    "INSERT": "ВСТАВИТЬ",
    "CHECK": "ПРОВЕРКА",
    "FULL": "ПОЛНОЕ",
    "POST": "ПОСТ",
    "LOST": "УТРАЧЕН",
}

# Files, packages, commands, routes.
PATHS = {
    "polaris_project_report_v2.pdf": "полярис_отчёт_о_проекте_в2.пдф",
    "polaris_project_report.pdf": "полярис_отчёт_о_проекте.пдф",
    "scripts/polaris-relying-party.py": "сценарии/полярис-доверяющая-сторона.пи",
    "scripts/polaris-wallet.py": "сценарии/полярис-кошелёк.пи",
    "polaris_card/card_profile.py": "полярис_карта/профиль_карты.пи",
    "oid4vp-1final-verifier-haip-test-plan": "оид4вп-1финал-верификатор-хаип-план-тестов",
    "polaris migrate-population": "полярис мигрировать-население",
    "--pqc-provider oqs": "--пкк-поставщик окс",
    "--dev-placeholder": "--разр-заглушка",
    "polaris-sdk-python": "полярис-сдк-питон",
    "polaris-registry/1": "полярис-реестр/1",
    "polaris-sdk-ts": "полярис-сдк-тс",
    "polaris-oid4vp": "полярис-оид4вп",
    "polaris-verify": "полярис-проверка",
    "polaris-*/1": "полярис-*/1",
    "/api/v1/exchange": "/апи/в1/обмен",
    "/api/v1/verify": "/апи/в1/проверка",
    "01_schema.sql": "01_схема.скл",
    "12_v7_constraints.sql": "12_в7_ограничения.скл",
    "docs/STRANGER-PATH.md": "документы/ПУТЬ-ПОСТОРОННЕГО.мд",
    "emulator.py": "эмулятор.пи",
    "MISSION.md": "МИССИЯ.мд",
    "README": "ЧИТАЙМЕНЯ",
}

# Standards, organisations, products, languages, acronyms.
NAMES = {
    "Certificate Transparency": "Прозрачности Сертификатов",
    "OpenID Foundation": "Фонда ОпенАйДи",
    "Project Wycheproof": "проекта Вайчпруф",
    "walt.id Wallet API v2": "Уолт.ид Воллет ППИ в2",
    "Module-LWE": "Модуль-ОСО",
    "Module-SIS": "Модуль-КЦЗ",
    "SLH-DSA-128s": "СЛХ-ДСА-128с",
    "SLH-DSA-256s": "СЛХ-ДСА-256с",
    "SLH-DSA": "СЛХ-ДСА",
    "ML-DSA-65": "МЛ-ДСА-65",
    "ML-DSA-87": "МЛ-ДСА-87",
    "ML-DSA-44": "МЛ-ДСА-44",
    "ML-DSA": "МЛ-ДСА",
    "SHA3-256": "ША3-256",
    "ISO/IEC": "ИСО/МЭК",
    "SD-JWT VC": "СД-ЖВТ ПУ",
    "SD-JWT": "СД-ЖВТ",
    "OpenID4VP": "ОИД4ВП",
    "OpenID": "ОпенАйДи",
    "PostgreSQL": "ПостгреСКЛ",
    "TypeScript": "ТайпСкрипт",
    "WebAuthn": "ВебАутн",
    "Plonky2": "Плонки2",
    "Poseidon": "Посейдон",
    "OpenSSL": "ОпенЭсЭсЭл",
    "liboqs": "либокс",
    "Wycheproof": "Вайчпруф",
    "walt.id": "Уолт.ид",
    "OAuth2": "ОАут2",
    "PKCS": "ПККС",
    "PKCE": "ПКСЕ",
    "X.509": "Х.509",
    "ES256": "ЕС256",
    "P-256": "П-256",
    "FIPS": "ФИПС",
    "CBOR": "КБОР",
    "JSON": "ДЖСОН",
    "HAIP": "ХАИП",
    "TLA+": "ТЛА+",
    "W3C": "В3К",
    "RFC": "РФС",
    "SDK": "КСР",
    "API": "ППИ",
    "SQL": "СКЛ",
    "TLS": "ТЛС",
    "KMS": "СУК",
    "NFC": "НФС",
    "PUK": "ПУК",
    "PIN": "ПИН",
    "ISO": "ИСО",
    "HTTP": "ХТТП",
    "Python": "Питон",
    "Java": "Джава",
    "Node": "Ноде",
    "Rust": "Раст",
    "Real ID": "Реал АйДи",
    "Polaris": "Полярис",
    "C1--C10": "С1--С10",
    "C10": "С10", "C1": "С1", "C2": "С2", "C3": "С3", "C4": "С4", "C5": "С5",
    "C6": "С6", "C7": "С7", "C8": "С8", "C9": "С9",
    "Atlas": "Атлас",
    "Athena": "Афина",
    "Metis": "Метида",
    "Myrmex": "Мирмекс",
    "Themis": "Фемида",
    "Merkle": "Меркла",
    "QR": "куар",
    "CI": "НИ",
    "ZK": "НР",
    "VC": "ПУ",
}

ALL = {}
for table in (ENTITIES, CHECKS, CODE, PATHS, NAMES):
    ALL.update(table)


#: Patterned forms the table cannot enumerate: release-candidate and version stamps.
REGEX = [
    (r"(?<![A-Za-z0-9])v(?=9\.\d)", "в"),          # v9.353 -> в9.353
    (r"(?<=\d)-rc\.(?=\d)", "-кв."),               # 1.0.0-rc.7 -> 1.0.0-кв.7
]
