"""
test_canonical_equivalence.py — the canonical-signing equivalence oracle.

Polaris has five signed statement types. Each is signed by the application over a
canonical byte string, and verified OFFLINE by scripts/polaris-verify.py, which
reconstructs that same byte string independently. If the two sides ever disagree on a
single byte -- a key added on one side, a separator changed, a sort dropped -- the
application keeps signing happily while EVERY offline verification fails, silently.
That is the subtlest and highest-impact failure mode in the system, and it is exactly
the kind a single worked example does not catch.

This is a differential + metamorphic oracle over the two canonicalizations. For each
signed type it treats the app-side builder and the verify-side builder as two
independent implementations of one spec and, over inputs generated by Hypothesis
(unicode that forces JSON escaping, key reorderings, nested structures, integer
boundaries, stray keys), asserts the properties that MUST hold:

  - cross-implementation equivalence: app(body) == verify(body), byte for byte;
  - determinism: a builder is a pure function of its input;
  - key-order invariance: the output does not depend on input key order (sorted keys);
  - signature-envelope exclusion: signature_hex / public_key_hex and any other extra key
    never enter the signed bytes (a security property -- the signature cannot sign itself);
  - JSON round-trip stability: serializing and reparsing the body does not perturb it;
  - canonical form: the output is compact (no ", " or ": ") and its keys are sorted.

It is deliberately crypto-free. Byte equality of the signed statement is what makes an
app signature verifiable offline, and it holds independent of the signing key, so the
oracle needs no liboqs and runs in the ordinary product-test job. The real ML-DSA-65
round-trip -- that a signature over app(body) verifies against SHA3-256(verify(body)) --
is proven per type by the pqc-real drills (the manifest, offline-status, epoch-revocation
and two-instance drills). check_canonical_equivalence pins this oracle and statically
compares the two sides' key lists.
"""
import importlib.util
import json
import os
import unittest

from hypothesis import given, settings, strategies as st, HealthCheck

import app as flask_app

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load_verifier():
    spec = importlib.util.spec_from_file_location(
        "polaris_verify_oracle", os.path.join(_ROOT, "scripts", "polaris-verify.py"))
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


_V = _load_verifier()


# Each signed type: its ordered signed keys, adapters that drive each side from one
# generated body dict, and any field the app builder holds CONSTANT rather than reading
# from the body. The status assertion is the one that hardcodes `format` (its app builder
# takes positional args and injects the constant), so the body must carry that same
# constant for the two sides to agree -- which is exactly what happens in the real flow.
SIGNED_TYPES = {
    "federation-manifest": {
        "keys": ["format", "authority", "anchors", "attestations", "epoch",
                 "revocation", "issued_at", "expires_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._manifest_statement(b),
        "verify": lambda b: _V._manifest_canonical(b),
    },
    # P9.5 (v9.348): the attesting agency's own signature over a federation trust edge.
    "trust-attestation": {
        "keys": ["format", "attesting_agency_id", "attested_agency_id",
                 "attested_public_key_hex", "context_id", "attested_date",
                 "valid_until", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._attestation_statement(b),
        "verify": lambda b: _V._attestation_canonical(b),
    },
    # P9.1 (v9.349): the issuer's binding of a holder key, and the holder's own proof.
    "holder-binding": {
        "keys": ["format", "token_value", "holder_public_key_hex", "holder_algorithm",
                 "bound_at", "status", "issued_at", "expires_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._holder_binding_statement(b),
        "verify": lambda b: _V._holder_binding_canonical(b),
    },
    "holder-proof": {
        "keys": ["format", "token_value", "context_id", "verifier_nonce", "issued_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._holder_proof_statement(b),
        "verify": lambda b: _V._holder_proof_canonical(b),
    },
    # P9.8 (v9.354): delegation. Signed by the HOLDER's key and the AGENT's, never the
    # issuer's, but the app must build the identical bytes in order to verify one.
    "agent-grant": {
        "keys": ["format", "grant_id", "agent_public_key_hex", "agent_algorithm", "actions",
                 "limits", "context_id", "issued_at", "expires_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._agent_grant_statement(b),
        "verify": lambda b: _V._agent_grant_canonical(b),
    },
    "grant-revocation": {
        "keys": ["format", "grant_id", "revoked_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._grant_revocation_statement(b),
        "verify": lambda b: _V._grant_revocation_canonical(b),
    },
    "agent-proof": {
        "keys": ["format", "grant_id", "action", "service_nonce", "issued_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._agent_proof_statement(b),
        "verify": lambda b: _V._agent_proof_canonical(b),
    },
    # P9.2 (v9.350): the published anonymity set.
    "epoch-leaves": {
        "keys": ["format", "authority", "epoch_id", "context_id", "merkle_root",
                 "leaf_count", "leaves_root_hex", "issued_at", "expires_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._epoch_leaves_statement(b),
        "verify": lambda b: _V._epoch_leaves_canonical(b),
    },
    "epoch-checkpoint": {
        "keys": ["format", "authority", "epoch", "prev", "as_of",
                 "issued_at", "expires_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._epoch_checkpoint_statement(b),
        "verify": lambda b: _V._epoch_checkpoint_canonical(b),
    },
    "revocation-feed": {
        "keys": ["format", "authority", "epoch_number", "as_of", "revoked_root_hex",
                 "revoked_count", "revoked_leaves", "issued_at", "expires_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._revocation_feed_statement(b),
        "verify": lambda b: _V._revocation_feed_canonical(b),
    },
    "status-assertion": {
        "keys": ["format", "token_value", "status", "issued_at", "expires_at"],
        "fixed": {"format": flask_app._STATUS_ASSERTION_FORMAT},
        "app": lambda b: flask_app._status_assertion_statement(
            b.get("token_value"), b.get("status"), b.get("issued_at"), b.get("expires_at")),
        "verify": lambda b: _V._status_assertion_canonical(b),
    },
    "transparency-sth": {
        "keys": ["format", "log_id", "tree_size", "root_hash_hex", "timestamp"],
        "fixed": {},
        "app": lambda b: flask_app._sth_statement(b),
        "verify": lambda b: _V._sth_canonical(b),
    },
    "federation-status-bundle": {
        "keys": ["format", "publisher", "members_root_hex", "member_count",
                 "issued_at", "expires_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._status_bundle_statement(b),
        "verify": lambda b: _V._status_bundle_canonical(b),
    },
    "exchange-receipt": {
        "keys": ["format", "requester", "responder", "context_id", "request_hash",
                 "response_hash", "authorized_via", "occurred_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._exchange_receipt_statement(b),
        "verify": lambda b: _V._exchange_receipt_canonical(b),
    },
    # polaris-exchange-mint/1 (P8.2b): CLIENT-built, INSTANCE-verified -- the same byte
    # equality matters in the other direction, so it is held to the same oracle.
    "exchange-mint": {
        "keys": ["format", "requester_public_key_hex", "context_id", "request_hash",
                 "response_hash", "responder_agency_id", "occurred_at"],
        "fixed": {},
        "app": lambda b: flask_app._exchange_mint_statement(b),
        "verify": lambda b: _V._exchange_mint_canonical(b),
    },
    # polaris-timestamp/1 (P8.7a): the timestamp authority's binding of a digest to an instant.
    "timestamp": {
        "keys": ["format", "authority", "digest_hex", "digest_algorithm", "nonce", "issued_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._timestamp_statement(b),
        "verify": lambda b: _V._timestamp_canonical(b),
    },
    # polaris-registry/1 (P8.3): the signed discovery artifact over the Athena authority layer.
    "registry": {
        "keys": ["format", "publisher", "instance", "authorities", "contexts", "trust",
                 "relying_parties", "issued_at", "expires_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._registry_statement(b),
        "verify": lambda b: _V._registry_canonical(b),
    },
    # polaris-exchange-request/1 (P8.2d): CLIENT-built, GATEWAY-verified -- held to the oracle
    # in the other direction, like the mint request.
    "exchange-request": {
        "keys": ["format", "requester", "target", "context_id", "request_hash", "nonce", "issued_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._exchange_request_statement(b),
        "verify": lambda b: _V._exchange_request_canonical(b),
    },
    # polaris-signed-document/1 (P8.5): the portable document container.
    "signed-document": {
        "keys": ["format", "document", "signer", "on_behalf_of", "purpose", "signed_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._signed_document_statement(b),
        "verify": lambda b: _V._signed_document_canonical(b),
    },
    # polaris-id-token/1 (P8.4): the auth broker's ID token, signed by the issuing agency.
    "id-token": {
        "keys": ["format", "iss", "sub", "aud", "nonce", "context_id", "disclosure_level", "acr",
                 "enrollment", "auth_time", "iat", "exp", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._id_token_statement(b),
        "verify": lambda b: _V._id_token_canonical(b),
    },
    # polaris-trust-list/1 (P8.7b): the signed authority key register.
    "trust-list": {
        "keys": ["format", "publisher", "keys", "issued_at", "expires_at", "algorithm"],
        "fixed": {},
        "app": lambda b: flask_app._trust_list_statement(b),
        "verify": lambda b: _V._trust_list_canonical(b),
    },
}


def _json_values():
    """Any value a signed field may hold: recursive but bounded, and deliberately
    adversarial -- None, booleans, integers across the 64-bit boundaries, unicode that
    forces JSON escaping, and nested lists/dicts whose element and key order is a drift
    trap. No floats: the real statements carry none, and they would only add NaN/Infinity
    noise that both sides serialize identically anyway."""
    scalar = st.one_of(
        st.none(),
        st.booleans(),
        st.integers(min_value=-(2 ** 63), max_value=2 ** 64),
        st.text(st.characters(min_codepoint=1, max_codepoint=0x10FFFF,
                              blacklist_categories=("Cs",)), max_size=40),
    )
    return st.recursive(
        scalar,
        lambda children: st.one_of(
            st.lists(children, max_size=4),
            st.dictionaries(st.text(min_size=1, max_size=8), children, max_size=4),
        ),
        max_leaves=8,
    )


def _bodies_for(spec):
    """A body mapping each signed key to a generated value, with the app-controlled
    constants pinned. Keys are always present (present-with-null is distinct from absent,
    and every builder reads with .get())."""
    fixed = spec.get("fixed", {})
    mapping = {k: (st.just(fixed[k]) if k in fixed else _json_values()) for k in spec["keys"]}
    return st.fixed_dictionaries(mapping)


_SETTINGS = settings(max_examples=250, deadline=None,
                     suppress_health_check=[HealthCheck.too_slow])


def _slug(name):
    return name.replace("-", "_")


def _make_methods(name, spec):
    app_fn, ver_fn, keys = spec["app"], spec["verify"], spec["keys"]
    bodies = _bodies_for(spec)

    @given(body=bodies)
    @_SETTINGS
    def cross_impl_equivalence(self, body):
        self.assertEqual(app_fn(body), ver_fn(body),
                         "%s: the app signer and the offline verifier disagree on the canonical bytes" % name)

    @given(body=bodies)
    @_SETTINGS
    def deterministic(self, body):
        self.assertEqual(app_fn(body), app_fn(dict(body)))
        self.assertEqual(ver_fn(body), ver_fn(dict(body)))

    @given(body=bodies, data=st.data())
    @_SETTINGS
    def key_order_invariant(self, body, data):
        shuffled = dict(data.draw(st.permutations(list(body.items()))))
        self.assertEqual(app_fn(shuffled), app_fn(body),
                         "%s: the app's signed bytes depend on input key order (not sorted?)" % name)
        self.assertEqual(ver_fn(shuffled), ver_fn(body),
                         "%s: the verifier's canonical bytes depend on input key order" % name)

    @given(body=bodies,
           extra=st.dictionaries(
               st.text(min_size=1, max_size=12).filter(lambda k: k not in keys),
               _json_values(), max_size=4))
    @_SETTINGS
    def signature_envelope_excluded(self, body, extra):
        # The signature envelope, and any other stray key, must never change the signed
        # bytes -- otherwise the signature would sign (part of) itself.
        extra.setdefault("signature_hex", "deadbeef")
        extra.setdefault("public_key_hex", "cafe")
        polluted = dict(body)
        polluted.update(extra)
        self.assertEqual(app_fn(polluted), app_fn(body),
                         "%s: an extra key changed the app's signed bytes (envelope leak)" % name)
        self.assertEqual(ver_fn(polluted), ver_fn(body),
                         "%s: an extra key changed the verifier's canonical bytes" % name)

    @given(body=bodies)
    @_SETTINGS
    def json_roundtrip_stable(self, body):
        reparsed = json.loads(json.dumps(body))
        self.assertEqual(app_fn(reparsed), app_fn(body))
        self.assertEqual(ver_fn(reparsed), ver_fn(body))

    @given(body=bodies)
    @_SETTINGS
    def canonical_form(self, body):
        out = app_fn(body)
        self.assertIsInstance(out, bytes)
        # The output is exactly the compact, sorted-key canonicalization of its own
        # content: re-serializing the parsed output under the canonical settings
        # reproduces it byte for byte. This catches a non-compact separator or an
        # unsorted key without mistaking a VALUE that merely contains ", " for a
        # separator (a naive substring check would; Hypothesis found that at once).
        parsed = json.loads(out)
        recanon = json.dumps(parsed, sort_keys=True, separators=(",", ":")).encode("utf-8")
        self.assertEqual(out, recanon,
                         "%s: output is not the compact, sorted-key canonical form" % name)
        self.assertEqual(list(parsed.keys()), sorted(parsed.keys()),
                         "%s: top-level keys are not in sorted order" % name)

    s = _slug(name)
    return {
        "test_%s_cross_impl_equivalence" % s: cross_impl_equivalence,
        "test_%s_deterministic" % s: deterministic,
        "test_%s_key_order_invariant" % s: key_order_invariant,
        "test_%s_signature_envelope_excluded" % s: signature_envelope_excluded,
        "test_%s_json_roundtrip_stable" % s: json_roundtrip_stable,
        "test_%s_canonical_form" % s: canonical_form,
    }


# One TestCase per signed type, each carrying the six metamorphic properties. Built inside
# a function so the loop variables never leak into the module namespace, where unittest
# would discover a stray name as a second alias for the last class and run its cases twice.
def _install_oracle_classes():
    for name, spec in SIGNED_TYPES.items():
        cls = type("CanonicalOracle_%s" % _slug(name), (unittest.TestCase,), _make_methods(name, spec))
        globals()[cls.__name__] = cls


_install_oracle_classes()


class CanonicalEquivalenceCoverage(unittest.TestCase):
    """The oracle must cover every signed type that exists, so a sixth type added later
    without an oracle case fails here rather than sailing through unverified."""

    def test_covers_every_signed_format_in_the_verifier(self):
        with open(os.path.join(_ROOT, "scripts", "polaris-verify.py")) as f:
            verify_src = f.read()
        # Every `polaris-*/1` format literal the verifier knows must have an oracle case,
        # except formats with no app-side statement builder to differentially test here:
        # the authenticity pack (SHA3-256(token_value), no canonical-JSON builder; covered by
        # the vectors and every drill), the witness cosignature (signed by an independent
        # witness, not the app; agreement proven by the gossip drill), and the publication
        # receipt (a bundle whose only signed part is the LEDGER's own STH -- itself the
        # transparency-sth type, already covered -- with the rest an inclusion proof;
        # agreement proven by the publication drill).
        import re
        formats = set(re.findall(r'"(polaris-[a-z-]+/1)"', verify_src))
        covered = {
            "polaris-federation-manifest/1", "polaris-epoch-checkpoint/1",
            "polaris-revocation-feed/1", "polaris-status-assertion/1",
            "polaris-transparency-sth/1", "polaris-federation-status-bundle/1",
            "polaris-exchange-receipt/1", "polaris-exchange-mint/1", "polaris-timestamp/1",
            "polaris-registry/1", "polaris-exchange-request/1",
            "polaris-signed-document/1", "polaris-id-token/1",
            "polaris-trust-list/1", "polaris-trust-attestation/1",
            "polaris-holder-binding/1", "polaris-holder-proof/1", "polaris-epoch-leaves/1",
            # P9.8: delegation. Signed by the holder's key and the agent's, not the issuer's,
            # but the app builds the identical bytes to VERIFY one, so the oracle covers them.
            "polaris-agent-grant/1", "polaris-grant-revocation/1", "polaris-agent-proof/1",
        }
        not_app_signed = {"polaris-authenticity-pack/1", "polaris-transparency-cosignature/1",
                          "polaris-transparency-publication/1", "polaris-published-head/1",
                          # P8.6: the holder-side wrapper and its QR framing carry no app signature
                          "polaris-presentation/1", "polaris-qr/1",
                          # P9.4: a domain-separation TAG inside a SHA3-256 preimage, not a
                          # signed artifact. It matches the format-string shape on purpose, so
                          # that a handle cannot be confused with another value in the protocol,
                          # and it is named here rather than reshaped to dodge this scan.
                          "polaris-pairwise/1"}
        missing = formats - covered - not_app_signed
        self.assertFalse(missing, "signed formats with no canonical-equivalence oracle case: %s" % missing)


if __name__ == "__main__":
    unittest.main()
