#!/usr/bin/env python3
"""
polaris-make-vectors.py — generate the PUBLISHED authenticity test vectors.

These vectors are the fixed, external artifact that lets anyone re-verify a
Polaris ML-DSA-65 credential OFFLINE with scripts/polaris-verify.py (or their own
FIPS-204 verifier) and confirm the two verdicts that matter: a genuine pack
verifies, and every tampered variant FAILS. CI re-verifies them under the app's
real witnesses (liboqs + cryptography/OpenSSL) on every release, so a broken
verifier or a silent interop regression turns CI red — a path that runs without
anyone watching, not a document claiming it does.

Signer selection, most-canonical first:
  1. liboqs (`oqs`)          — the exact library the app signs with.
  2. dilithium-py            — an independent pure-Python FIPS-204 impl, so the
                               vectors can be produced with no native library and
                               still verify cross-implementation under liboqs.
The vector records which implementation produced it (`_vector.provenance`); the
crypto is standard ML-DSA-65 over SHA3-256(token_value) with an empty context, so
the verdict is implementation-independent.

Usage:  python3 scripts/polaris-make-vectors.py [--out vectors]
"""
import argparse
import hashlib
import json
import os
import sys

_ALG = "ML-DSA-65"
_PLACEHOLDER = "DETERMINISTIC-PLACEHOLDER-SHA3-256"
_DIGEST_CONSTRUCTION = 'SHA3-256(token_value.encode("utf-8"))'


def _digest(token_value: str) -> bytes:
    return hashlib.sha3_256(token_value.encode("utf-8")).digest()


def _signer():
    """Return (name, keygen()->(pk,sk), sign(sk,digest)->sig). Prefer liboqs."""
    try:
        import oqs  # type: ignore

        def keygen():
            with oqs.Signature(_ALG) as s:
                pk = s.generate_keypair()
                sk = s.export_secret_key()
                return bytes(pk), bytes(sk)

        def sign(sk, digest):
            with oqs.Signature(_ALG, secret_key=sk) as s:
                return bytes(s.sign(digest))

        return ("liboqs", keygen, sign)
    except Exception:
        pass
    try:
        from dilithium_py.ml_dsa import ML_DSA_65  # type: ignore

        def keygen():
            pk, sk = ML_DSA_65.keygen()
            return bytes(pk), bytes(sk)

        def sign(sk, digest):
            return bytes(ML_DSA_65.sign(sk, digest))  # ctx=b"" default (pure ML-DSA)

        return ("dilithium-py (independent FIPS-204 impl)", keygen, sign)
    except Exception:
        return (None, None, None)


def _pack(token_value, sig, pk, name, expect, provenance, note):
    return {
        "format": "polaris-authenticity-pack/1",
        "token_value": token_value,
        "algorithm": _ALG,
        "signature_hex": sig.hex(),
        "public_key_hex": pk.hex(),
        "digest_construction": _DIGEST_CONSTRUCTION,
        "_vector": {
            "name": name,
            "expect": expect,  # "valid" | "invalid"
            "provenance": provenance,
            "note": note,
        },
    }


def _write(out_dir, obj):
    path = os.path.join(out_dir, obj["_vector"]["name"] + ".json")
    with open(path, "w") as f:
        json.dump(obj, f, indent=2, sort_keys=True)
        f.write("\n")
    return path


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate published Polaris authenticity vectors.")
    ap.add_argument("--out", default="vectors")
    args = ap.parse_args(argv)
    os.makedirs(args.out, exist_ok=True)

    name, keygen, sign = _signer()
    written = []

    # The placeholder vector needs no signer at all — it is a SHA3 binding, and
    # its whole point is that the verifier must REFUSE to call it authentic.
    tokp = "POLARIS-VECTOR-PLACEHOLDER-0001"
    placeholder = {
        "format": "polaris-authenticity-pack/1",
        "token_value": tokp,
        "algorithm": _PLACEHOLDER,
        "signature_hex": _digest(tokp).hex(),
        "public_key_hex": None,
        "digest_construction": _DIGEST_CONSTRUCTION,
        "real_signature": False,
        "_vector": {
            "name": "placeholder",
            "expect": "invalid",
            "provenance": "dependency-free SHA3-256 binding (the dev/CI placeholder, not a signature)",
            "note": "a verifier MUST report this as not-authenticatable, never as a green check",
        },
    }
    written.append(_write(args.out, placeholder))

    if name is None:
        sys.stderr.write(
            "no ML-DSA-65 signer available (install liboqs-python or dilithium-py); "
            "wrote the placeholder vector only\n")
        print("\n".join(written))
        return 0

    prov = "generated by %s; re-verifiable by any FIPS-204 ML-DSA-65 verifier" % name

    tok = "POLARIS-VECTOR-VALID-0001"
    pk, sk = keygen()
    sig = sign(sk, _digest(tok))
    written.append(_write(args.out, _pack(
        tok, sig, pk, "ml-dsa-65-valid", "valid", prov,
        "a genuine ML-DSA-65 signature over SHA3-256(token_value); MUST verify")))

    # Tampered signature: flip one byte. MUST fail.
    bad_sig = bytearray(sig)
    bad_sig[0] ^= 0x01
    written.append(_write(args.out, _pack(
        tok, bytes(bad_sig), pk, "ml-dsa-65-tampered-signature", "invalid", prov,
        "the valid signature with one byte flipped; MUST fail")))

    # Tampered token: same sig+key, different signed message. MUST fail.
    written.append(_write(args.out, _pack(
        tok + "-ALTERED", sig, pk, "ml-dsa-65-tampered-token", "invalid", prov,
        "a genuine signature presented against a DIFFERENT token_value; MUST fail")))

    # Wrong key: valid sig, unrelated public key. MUST fail.
    pk2, _sk2 = keygen()
    written.append(_write(args.out, _pack(
        tok, sig, pk2, "ml-dsa-65-wrong-key", "invalid", prov,
        "a genuine signature checked against an UNRELATED public key; MUST fail")))

    print("signer: %s" % name)
    print("\n".join(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
