#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Egor Khaklin and the Polaris contributors
"""polaris-sbom-enrich.py -- make a release SBOM valid SPDX 2.3 with the NTIA minimum elements.

The release SBOMs come from Trivy, the same version the CVE gate runs, so the bill of materials
describes what the scanner saw (check_sbom_trivy_matches_scan). Measured on v1.0.0-rc.70 with the
SPDX project's NTIA conformance checker, none of the six met the 2021 NTIA minimum elements, and
four were not valid SPDX 2.3: Trivy records a supplier only for Debian packages, gives the
document's subject and the binaries it finds no version, names its own vendor as the author, and
copies license names that are not on the SPDX License List (`public-domain`, `GPL-3.0-or-later
WITH Bison-exception`) into license expressions. This fixes each from facts the document or the
release already holds, and from nothing else:

  - the SBOM's subject (the image or lockfile the document DESCRIBES) and each component named
    with --ours (one this repository builds: the Caddy main module xcaddy generates, the
    lockfile): the release version, and Polaris ID as the supplier;
  - a component with a package URL: the supplier the URL names (the PyPI project, the
    distribution that built the package, the Go module's owner). A supplier Trivy already
    recorded (the Debian maintainers) is kept;
  - an operating system: its distribution;
  - a binary that contains one module (gosu): that module's version and supplier;
  - a license name the SPDX License List does not carry: a LicenseRef- defined under
    hasExtractedLicensingInfos with the name the package gave it. An exception the list does not
    carry is joined with AND, because SPDX 2.3 has no reference form for an exception;
  - the document's author: Polaris ID, beside the tools that wrote it.

    polaris-sbom-enrich.py --version 1.0.0-rc.71 --ours requirements.txt sbom/sbom-python.spdx.json

The license list is the one the SPDX tools validate against (the license-expression package the
checker installs, from .github/sbom/requirements.txt), so a name is kept exactly when the checker
would accept it. Rewrites each file in place. Exits 1, naming every component, when any is still
missing a version or a supplier, so a release cannot carry an SBOM this left short.
"""
from __future__ import annotations

import argparse
import json
import re
import sys

POLARIS = "Organization: Polaris ID (https://github.com/EgorKhaklin/polaris-id)"
TOOL = "Tool: polaris-sbom-enrich-%s"
NOASSERTION = "NOASSERTION"
DISTROS = {
    "alpine": "Organization: Alpine Linux (https://alpinelinux.org)",
    "debian": "Organization: Debian (https://www.debian.org)",
}
GO_AUTHORS = "Organization: The Go Authors (https://go.dev)"
CODE_HOSTS = ("github.com", "gitlab.com", "bitbucket.org")
COMMENT = ("Generated by Trivy. Each version and supplier Trivy left out was filled by "
           "scripts/polaris-sbom-enrich.py from the component's package URL, its distribution, "
           "the module a binary contains, or the release itself; each license name the SPDX "
           "License List does not carry is a LicenseRef defined below with that name.")
REF_COMMENT = ("The name the package's own metadata gives this license. It is not on the SPDX "
               "License List; the text is in the package's copyright file.")
_TOKEN = re.compile(r"\(|\)|[^\s()]+")
_REF = re.compile(r"^LicenseRef-[A-Za-z0-9.-]+$")


def _missing(value):
    return value in (None, "", NOASSERTION)


def _purl(pkg):
    for ref in pkg.get("externalRefs") or ():
        if ref.get("referenceType") == "purl":
            return ref.get("referenceLocator") or ""
    return ""


def go_supplier(module):
    """The owner a Go module path names, or None for a path with no host (a main module)."""
    if module == "stdlib":
        return GO_AUTHORS
    parts = module.split("/")
    host = parts[0]
    if "." not in host or len(parts) < 2:
        return None
    if host == "gopkg.in":
        # gopkg.in/pkg.vN serves github.com/go-pkg/pkg; gopkg.in/user/pkg.vN, github.com/user/pkg.
        owner = parts[1] if len(parts) > 2 else "go-" + parts[1].split(".v")[0]
        return "Organization: %s (https://github.com/%s)" % (owner, owner)
    if host in CODE_HOSTS:
        return "Organization: %s (https://%s/%s)" % (parts[1], host, parts[1])
    return "Organization: %s (https://%s)" % (host, host)


def purl_supplier(purl, name=""):
    """The supplier a package URL names, or None when it names none this knows."""
    if not purl.startswith("pkg:"):
        return None
    kind, _, rest = purl[4:].partition("/")
    path = rest.split("@", 1)[0].split("?", 1)[0]
    if kind == "pypi" and path:
        return "Organization: %s project (https://pypi.org/project/%s/)" % (path, path)
    if kind in ("apk", "deb"):
        return DISTROS.get(path.split("/", 1)[0])
    if kind == "golang" and path:
        # The package name keeps the module path's case; the URL is lowercased.
        return go_supplier(name if name.lower() == path else path)
    return None


def enrich(doc, version, ours=()):
    """Fill the document in place; return the names of components still missing a field."""
    me = doc.get("SPDXID")
    rels = doc.get("relationships") or ()
    subjects = {r.get("relatedSpdxElement") for r in rels
                if r.get("spdxElementId") == me and r.get("relationshipType") == "DESCRIBES"}
    subjects.update(doc.get("documentDescribes") or ())
    packages = doc.get("packages") or []
    for pkg in packages:
        name = pkg.get("name", "")
        if pkg.get("SPDXID") in subjects or name in ours:
            if _missing(pkg.get("versionInfo")):
                pkg["versionInfo"] = version
            pkg["supplier"] = POLARIS
        elif _missing(pkg.get("supplier")):
            if pkg.get("primaryPackagePurpose") == "OPERATING-SYSTEM":
                found = DISTROS.get(name)
            else:
                found = purl_supplier(_purl(pkg), name)
            if found:
                pkg["supplier"] = found
    # A binary Trivy records as a file that CONTAINS exactly one module is that module's build.
    by_id = {p.get("SPDXID"): p for p in packages}
    contains = {}
    for r in rels:
        if r.get("relationshipType") == "CONTAINS" and r.get("relatedSpdxElement") in by_id:
            contains.setdefault(r.get("spdxElementId"), []).append(by_id[r["relatedSpdxElement"]])
    for pkg in packages:
        inner = contains.get(pkg.get("SPDXID")) or []
        if pkg.get("primaryPackagePurpose") == "APPLICATION" and not _purl(pkg) and len(inner) == 1:
            if _missing(pkg.get("versionInfo")) and not _missing(inner[0].get("versionInfo")):
                pkg["versionInfo"] = inner[0]["versionInfo"]
            if _missing(pkg.get("supplier")) and not _missing(inner[0].get("supplier")):
                pkg["supplier"] = inner[0]["supplier"]
    info = doc.setdefault("creationInfo", {})
    tools = [c for c in info.get("creators") or () if c.startswith("Tool:")
             and not c.startswith(TOOL % "")]
    info["creators"] = [POLARIS] + tools + [TOOL % version]
    info["comment"] = COMMENT
    return [p.get("name", p.get("SPDXID", "?")) for p in packages
            if _missing(p.get("versionInfo")) or _missing(p.get("supplier"))]


def license_expression(expr, is_license, is_exception, refs):
    """The expression with every name off the SPDX lists as a LicenseRef; refs gains each one.

    refs maps a name, lowercased, to [its LicenseRef id, the name as first written].
    """
    if expr in (None, "", NOASSERTION, "NONE"):
        return expr
    # Trivy splits a license written with a space ("Public Domain") into two joined by AND.
    expr = re.sub(r"\bPublic AND Domain\b", "Public-Domain", expr)
    out = []
    for tok in _TOKEN.findall(expr):
        op = tok.upper()
        if tok in ("(", ")") or op in ("AND", "OR", "WITH"):
            out.append(op)
            continue
        if out and out[-1] == "WITH":
            if is_exception(tok):
                out.append(tok)
                continue
            out[-1] = "AND"
        if is_license(tok) or (_REF.match(tok) and tok.lower() in refs):
            out.append(tok)
            continue
        key = tok.lower()
        if key not in refs:
            base = "LicenseRef-" + (re.sub(r"[^A-Za-z0-9.]+", "-", tok).strip("-") or "unnamed")
            taken = {r[0].lower() for r in refs.values()}
            ref, n = base, 2
            while ref.lower() in taken:
                ref, n = "%s-%d" % (base, n), n + 1
            refs[key] = [ref if not _REF.match(tok) else tok, tok]
        out.append(refs[key][0])
    return " ".join(out).replace("( ", "(").replace(" )", ")")


def repair_licenses(doc, is_license, is_exception):
    """Rewrite each package's license expressions to validate; return how many changed."""
    refs = {}
    for info in doc.get("hasExtractedLicensingInfos") or ():
        if _REF.match(info.get("licenseId") or ""):
            refs[info["licenseId"].lower()] = [info["licenseId"], info["licenseId"]]
    known = set(refs)
    changed = 0
    for pkg in doc.get("packages") or ():
        for field in ("licenseDeclared", "licenseConcluded"):
            before = pkg.get(field)
            after = license_expression(before, is_license, is_exception, refs)
            if after != before:
                pkg[field] = after
                changed += 1
    added = [{"licenseId": ref, "name": name, "extractedText": name, "comment": REF_COMMENT}
             for key, (ref, name) in sorted(refs.items(), key=lambda kv: kv[1][0])
             if key not in known]
    if added:
        doc["hasExtractedLicensingInfos"] = list(doc.get("hasExtractedLicensingInfos") or ()) + added
    return changed


def spdx_lists():
    """is_license and is_exception, answered exactly as the SPDX tools' validator answers them."""
    try:
        from license_expression import get_spdx_licensing
    except ImportError:
        sys.exit("polaris-sbom-enrich.py needs license-expression, the license list the SPDX "
                 "tools validate against: pip install --require-hashes -r .github/sbom/requirements.txt")
    licensing = get_spdx_licensing()
    cache = {}

    def clean(expr):
        if expr not in cache:
            info = licensing.validate(expr)
            cache[expr] = not info.errors and not info.invalid_symbols
        return cache[expr]
    return ((lambda tok: not tok.startswith("LicenseRef-") and clean(tok)),
            (lambda tok: not tok.startswith("LicenseRef-") and clean("MIT WITH " + tok)))


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Make a release SBOM valid SPDX 2.3 with the NTIA minimum elements.")
    ap.add_argument("--version", required=True,
                    help="the release version, for the subject and the components built here")
    ap.add_argument("--ours", action="append", default=[], metavar="NAME",
                    help="a component this repository builds (repeatable)")
    ap.add_argument("sboms", nargs="+")
    args = ap.parse_args(argv)
    is_license, is_exception = spdx_lists()
    failed = False
    for path in args.sboms:
        with open(path, encoding="utf-8") as fh:
            doc = json.load(fh)
        names = {p.get("name") for p in doc.get("packages") or ()}
        absent = [n for n in args.ours if n not in names]
        missing = enrich(doc, args.version, set(args.ours))
        rewritten = repair_licenses(doc, is_license, is_exception)
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(doc, fh, indent=2, sort_keys=True)
            fh.write("\n")
        if absent:
            failed = True
            print("%s: --ours names %s, which this SBOM does not list" % (path, ", ".join(absent)),
                  file=sys.stderr)
        if missing:
            failed = True
            print("%s: %d component(s) without a version or a supplier: %s"
                  % (path, len(missing), ", ".join(missing)), file=sys.stderr)
        elif not absent:
            print("%s: every component has a version and a supplier; %d license expression(s) "
                  "rewritten to the SPDX lists" % (path, rewritten))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
